export type Experience = {
  tag: string; slug: string; title: string; kicker: string; lead: string;
  blurb: string; region: string; days: string; from: string;
  img: string[]; highlights: string[]; stays: string[];
  season: number[]; // 12 values: 2=Quiet 3=Good 4=Great 5=Peak
  filterTag: string;
};

export const EXPERIENCE_DETAIL: Experience[] = [
  { tag:"01", slug:"safari", title:"Safari", kicker:"Wild Kenya", lead:"Private camps, ranger-led drives, the slow hours.", blurb:"Kenya invented the modern safari — and we choose the camps that still feel like it. Small footprints, private conservancies, guides who grew up on the land.", region:"Mara · Laikipia · Amboseli", days:"4–8 nights", from:"from $640 / night", img:["https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop"], highlights:["Private conservancy game drives","Walking safaris with Maasai trackers","Hot-air balloon over the Mara","Hide photography at waterholes"], stays:["Angama Mara","Sirikoi · Lewa","Tortilis · Amboseli"], season:[3,3,2,2,2,3,4,5,5,4,3,3], filterTag:"Wild" },
  { tag:"02", slug:"beach", title:"Beach Escapes", kicker:"Indian Ocean", lead:"Barefoot luxury, white sand, lazy reefs.", blurb:"The Kenyan coast moves at the pace of the tide. We send you to the stretches where the dhow boys still know everyone, and the beach reads like a private one.", region:"Diani · Watamu · Lamu", days:"5–10 nights", from:"from $380 / night", img:["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop"], highlights:["Private dhow sunset sails","Kite-surf lessons in Diani","Marine reserve snorkeling","Swahili supper clubs at home"], stays:["The Majlis · Lamu","Almanara · Diani","Hemingways · Watamu"], season:[5,5,4,2,2,3,4,4,4,4,4,5], filterTag:"Coast" },
  { tag:"03", slug:"wellness", title:"Wellness", kicker:"Slow systems", lead:"Coastal retreats and bush spas — the gentle reset.", blurb:"We pair clinical rigor with a deeper, slower rhythm: yoga at sunrise, Ayurveda by the reef, breathwork under acacia trees.", region:"Watamu · Naivasha · Laikipia", days:"5–14 nights", from:"from $420 / night", img:["https://images.unsplash.com/photo-1545389336-cf090694435e?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=80&auto=format&fit=crop"], highlights:["Daily yoga with ocean view","Ayurveda-trained therapists","Forest bath in Karura","Digital-detox bush stays"], stays:["Medina Palms","Enashipai · Naivasha","Segera Retreat"], season:[4,4,3,2,2,4,4,4,5,5,4,4], filterTag:"Wellness" },
  { tag:"04", slug:"honeymoon", title:"Honeymoons", kicker:"For two", lead:"Bush, beach, and the quiet between.", blurb:"Our most-requested arc: a private guide in the Mara, a bush flight to Lamu, a stone house on the water. We tune every transfer so you never see the seams.", region:"Mara → Lamu (typical)", days:"8–12 nights", from:"from $9,400 / couple", img:["https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop"], highlights:["Private vehicle, end to end","Bush flight, no overland","Sunset dhow with chef","In-villa massage on arrival"], stays:["Sala's Camp","Peponi Hotel · Lamu","Sasaab · Samburu"], season:[5,4,3,2,2,3,4,5,5,4,3,4], filterTag:"Romance" },
  { tag:"05", slug:"nomad", title:"Digital Nomad Stays", kicker:"Long-stay", lead:"Homes with fibre, communities with rhythm.", blurb:"For the month-or-more crowd: vetted villas with proper fibre, co-working communities, a SIM card on your pillow, and a concierge who handles the residency paperwork.", region:"Nairobi · Diani · Watamu", days:"30–90 nights", from:"from $2,800 / month", img:["https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=900&q=80&auto=format&fit=crop"], highlights:["300+ Mbps verified","Co-working membership","Maid + chef on call","Visa paperwork handled"], stays:["Karen long-stays","Diani Beachfront villas","Watamu studios"], season:[4,4,4,3,3,4,5,5,5,4,4,4], filterTag:"Long-stay" },
  { tag:"06", slug:"family", title:"Family Journeys", kicker:"With kids", lead:"Logistics simplified, kid-tested camps.", blurb:"Giraffe Manor breakfasts, family suites with pools, doctors on call, and an itinerary that respects nap windows. We've sent 240+ families — we know what breaks.", region:"Nairobi · Mara · Watamu", days:"8–12 nights", from:"from $720 / day · family", img:["/single-mother-safari.jpg","/travel-family.jpg"], highlights:["Family-suite-only camps","Pools at every base","Kid-safe game drives","Pediatrician on call"], stays:["Giraffe Manor","Hemingways Watamu","Mara Bushtops"], season:[4,4,3,2,2,4,5,5,5,4,3,4], filterTag:"With Kids" },
  { tag:"07", slug:"villa", title:"Private Villas", kicker:"Whole-house", lead:"Hand-picked houses with crew.", blurb:"From a six-bed stone house in Lamu Old Town to a cliff-side villa above Watamu's marine park — staffed, stocked, and tuned for groups of 4 to 14.", region:"Lamu · Diani · Karen", days:"5–14 nights", from:"from $1,200 / night", img:["https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop"], highlights:["Full staff — chef, house, security","Pre-stocked groceries","Driver on standby","Private dhow on call"], stays:["Forodhani House","Alfajiri Villas","Robinson Island"], season:[5,5,4,2,2,3,4,4,4,4,4,5], filterTag:"Coast" },
  { tag:"08", slug:"photo", title:"Photography", kicker:"Right light", lead:"Guides, hides, and the right hours.", blurb:"Built with two former National Geographic guides — golden-hour vehicle setups, custom hides, full-frame days, and a backup hard-drive workflow at base camp.", region:"Mara · Samburu · Lamu", days:"6–10 nights", from:"from $980 / night", img:["https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop","https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop"], highlights:["Specialist photo guides","Custom mounts + bean bags","Drive-up hides","On-site editing suite"], stays:["Mara Plains Camp","Saruni Samburu","Lamu House"], season:[3,3,2,2,2,3,5,5,5,4,3,3], filterTag:"Wild" },
  { tag:"09", slug:"bucket-list", title:"Bucket List", kicker:"Giraffe Manor & beyond", lead:"The giraffe at the window, the balloon at dawn, the orphaned elephant — properly arranged.", blurb:"Some Kenya moments transcend travel. We've spent years getting early access, preferred bookings, and the best room in the house for these iconic experiences — so you don't have to leave it to chance.", region:"Nairobi · Mara · Laikipia", days:"6–10 nights", from:"from $1,400 / night", img:["/giraffe-manor.jpg","https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop"], highlights:["Giraffe Manor breakfast booking","Hot-air balloon · Mara dawn","DSWT Elephant Orphanage","Ol Pejeta rhino conservancy"], stays:["Giraffe Manor","Angama Mara","Ol Pejeta conservancy"], season:[4,4,3,2,2,4,5,5,5,4,3,4], filterTag:"Bucket List" },
];

export type DetailCopy = {
  parent: string; intro: string; why: string;
  whyHeadline: string; heroRegion: string; heroCaption: string; ctaCopy: string;
  bestMonths: string; groupSize: string; pace: string; altitude: string;
  activities: { title: string; desc: string }[];
  sampleDay: { t: string; title: string; note: string }[];
  forWhom: string[];
  notForWhom: string[];
  practical: [string, string][];
  pack: string[];
  honest: [string, string][];
  quotes: { who: string; body: string }[];
  lodges: { name: string; region: string; note: string; img: string }[];
  gallery: string[];
  relatedSlugs: string[];
};

export const DETAIL_COPY: Record<string, DetailCopy> = {
  safari: {
    parent: "Wild Kenya",
    heroRegion: "Wild Kenya · Mara · Laikipia · Amboseli",
    heroCaption: "Mara · Field 041",
    ctaCopy: "Draft my safari",
    intro: "Kenya invented the modern safari — and most of what passes for one now is still drawn from its template. We don't send anyone to the chain camps with 80 vehicles fighting for the same lion. We send you to private conservancies, to camps that move with the herds, to guides who grew up tracking these animals.",
    why: "A real safari in Kenya is quieter than you think. It's the slow drive, not the lion sighting. It's the long lunch under the acacia, the silence at the sundowner, the second cup of coffee at 5:30am because the day belongs to you. We choose camps that protect that — small, owner-run, deep inside conservancies where the rules tilt toward wildness, not tourism.",
    whyHeadline: "The slow drive, not the sighting.",
    bestMonths: "Jul – Oct", groupSize: "2 – 8 travellers", pace: "Slow · 2 drives a day", altitude: "1,500 – 2,000m",
    activities: [
      { title: "Game drives", desc: "Private conservancy drives from first light — your vehicle, your pace, your guide's eyes." },
      { title: "Walking safaris", desc: "On foot with Maasai trackers. The bush reads differently at ankle height." },
      { title: "Hot-air balloon", desc: "Dawn over the Mara at altitude. One hour. Champagne breakfast after." },
      { title: "Hide photography", desc: "Custom hides at waterholes. Big cats, patience, natural light." },
    ],
    sampleDay: [
      { t: "05:30", title: "Wake-up coffee", note: "Tray of coffee and rusks at your tent. Dawn breaks behind Olololo escarpment." },
      { t: "06:15", title: "Game drive", note: "Out before the light. Your guide reads tracks from last night. Cats are still moving." },
      { t: "09:30", title: "Bush breakfast", note: "Eggs cooked on a fire by the river. Tablecloth, real cutlery, no one for miles." },
      { t: "11:00", title: "Camp · siesta", note: "Back to base. A swim, a book, a nap. The bush gets loud at midday — we don't fight it." },
      { t: "13:00", title: "Long lunch", note: "Three courses under canvas. Guides at the table, talking through the morning." },
      { t: "16:00", title: "Second drive", note: "Out for the golden hours. This is when you'll see the things people come back for." },
      { t: "18:45", title: "Sundowner", note: "Gin and tonic on a kopje. The plains turn copper. The radio goes quiet." },
      { t: "20:00", title: "Dinner under stars", note: "Lanterns, a long table, the night sounds. Then escorted back to your tent." },
    ],
    forWhom: ["First-time safari seekers","Photographers and wildlife lovers","Couples seeking real remoteness","Families with patient kids"],
    notForWhom: ["Travellers who need a packed itinerary","Those who won't watch the weather","Anyone expecting 100 animals guaranteed","Checklist-first travellers"],
    practical: [["Visa","eVisa online · 72h"],["Vaccine","Yellow fever cert."],["Currency","USD · KES on arrival"],["Plug","Type G · UK style"],["Connectivity","Spotty by design"],["Tipping","Built into your plan"]],
    pack: ["Neutral khakis, greens, browns — no white, no bright blue","A warm fleece for dawn drives — yes, even at the equator","Closed shoes for walking safaris","A real camera, 200mm+ if you have one","Headlamp · sunglasses · wide-brim hat","Leave the safari hat with the leopard print at home"],
    honest: [["You won't see everything","Sometimes the leopard is asleep. The guides won't fake it. The slow days are part of the deal."],["April–May is wet","It's also empty and green and half-price. We'll tell you if it's your move."],["The big migration is a window","Late July through early October — and even then, it's where the herds choose, not where the brochures promise."],["No, you don't tip in dollars at the bar","We brief you fully before you land. None of that 'figure it out' nonsense."]],
    quotes: [
      { who: "Anna & Tom · honeymoon · 2025", body: "Selin moved us between three camps and we never saw a transfer in our lives. The Mara was a dream. Lamu finished us." },
      { who: "Karim family · 4 · 2025", body: "The first family trip where my kids were never bored and I never carried a single bag. The pediatrician on call thing is not a gimmick." },
      { who: "Maya · photographer · 2024", body: "The hides at Ol Pejeta and the photo guide in the Mara were the difference between a portfolio and a holiday." },
    ],
    lodges: [
      { name:"Angama Mara", region:"Mara Triangle · Mara", note:"Glass-fronted tents over the Oloololo escarpment. Slightly impossible views.", img:"https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop" },
      { name:"Sirikoi", region:"Lewa Conservancy · Laikipia", note:"Founder-run, four cottages. Walking, riding, and rhinos behind the fence line.", img:"https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop" },
      { name:"Sala's Camp", region:"Sand River · Mara", note:"Migration crossing point. Six tents, a long lunch table, no Wi-Fi by design.", img:"https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop" },
      { name:"Saruni Samburu", region:"Kalama Conservancy · Samburu", note:"Six lodges on a rocky kopje. Lions below, eagles above, near nobody.", img:"https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop" },
      { name:"Tortilis Camp", region:"Amboseli", note:"Kilimanjaro framed in the dining tent. Elephants pass at breakfast.", img:"https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop" },
      { name:"Mara Plains Camp", region:"Olare Motorogi · Mara", note:"Seven tents on raised decks. Specialist photo vehicles standard.", img:"https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=900&q=80&auto=format&fit=crop" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551632811-561732d1e306?w=900&q=80&auto=format&fit=crop",
    ],
    relatedSlugs: ["honeymoon","photo","family","wellness"],
  },

  beach: {
    parent: "Indian Ocean",
    heroRegion: "Indian Ocean · Diani · Watamu · Lamu",
    heroCaption: "Diani · Coral 002",
    ctaCopy: "Draft my coast trip",
    intro: "The Kenyan coastline runs for 536 kilometres and most of it is still quiet. We don't send you to the hotel strip. We send you to the stretches where the tides set the schedule, the dhow boys know your name by day two, and the reef sits ten minutes from your sun lounger.",
    why: "A good Kenya beach trip has nothing to do with sunbeds. It's a morning snorkel in water so clear you can read the bottom, an afternoon in a borrowed kayak, a Swahili supper in someone's courtyard. We choose properties where the staff have been there ten years and the sea views haven't been blocked yet.",
    whyHeadline: "The tide sets the schedule, not the other way.",
    bestMonths: "Dec – Mar · Oct – Nov", groupSize: "2 – 10 travellers", pace: "Slow · tidal rhythm", altitude: "Sea level",
    activities: [
      { title: "Private dhow sail", desc: "Sunset on the Indian Ocean, captain included. Cold drinks, no other boats, no itinerary." },
      { title: "Marine reserve snorkeling", desc: "Watamu and Kisite are among Africa's finest — turtles, coral gardens, whale sharks October to March." },
      { title: "Kite-surfing · Diani", desc: "The reef creates flat-water conditions most mornings. We book instructors who are as patient as the ocean." },
      { title: "Swahili supper club", desc: "A home kitchen in Lamu or Malindi — coconut curries, pilau, biryani. The best meal of your trip, guaranteed." },
    ],
    sampleDay: [
      { t: "06:30", title: "Sunrise swim", note: "The reef water is at its clearest before 8am. Mask and fins on the beach steps." },
      { t: "08:00", title: "Breakfast on the terrace", note: "Fresh papaya, Swahili mandazi, real Kenyan coffee. The dhow boys are already out." },
      { t: "09:30", title: "Snorkel or kayak", note: "Your choice. We pick the tide window. The marine park warden knows us." },
      { t: "12:00", title: "Long lunch", note: "Back to the shaded veranda. Grilled fish, cold Tusker, the ceiling fan overhead." },
      { t: "14:00", title: "Beach or book", note: "The serious rest. A hammock, a chapter, the sound of waves. No guilt." },
      { t: "16:30", title: "Dhow or walk", note: "Sunset sail or a quiet walk to the village market — your call, we've arranged both." },
      { t: "19:00", title: "Supper", note: "Swahili supper club if your timing's right. Otherwise dinner at a table six feet from the surf." },
      { t: "21:00", title: "Stars", note: "The coast has almost no light pollution. Pull a chair to the beach and count them." },
    ],
    forWhom: ["Couples wanting total quiet","Honeymooners after private beaches","Snorkelers, divers, kite-surfers","Families with confident swimmers"],
    notForWhom: ["Those needing reliable year-round weather (April rains)","Anyone allergic to sand and salt","City-energy seekers","Travellers who need WiFi 24/7"],
    practical: [["Visa","eVisa online · 72h"],["Vaccine","Yellow fever cert."],["Currency","KES · USD accepted widely at coast"],["Plug","Type G · UK style"],["Connectivity","Good in Diani, patchy in Lamu"],["Water","Bottled · always"]],
    pack: ["Rash guard and reef shoes","Biodegradable sunscreen — reef rules","A light sarong — covers mosques and beach bars equally","Prescription mask if you need one","Two swimsuits — drying time in humidity is real","A torch for beach walks after dark"],
    honest: [["April and May are wet","Properly wet. The coast shuts down. Plan around it — or get the low season price and gamble wisely."],["Jellyfish are seasonal","October–November in Diani. We'll tell you in advance. It's manageable but not nothing."],["Shared beaches in Diani","The beach is public. There will be vendors. A firm, friendly 'no thank you' works every time."],["Lamu has no cars","This is the point — it's also the constraint. You carry your own bags or pay a porter. Worth it completely."]],
    quotes: [
      { who: "Niamh & Patrick · honeymoon · 2025", body: "The Lamu stone house was the best accommodation of our lives. Selin got us the ground-floor room that looks into the courtyard. Perfect." },
      { who: "The Osei family · 6 · 2025", body: "Kids snorkeled every morning and slept every afternoon. The reef at Watamu is genuinely unlike anything we'd seen. We'll be back." },
      { who: "Layla · solo · 2024", body: "Solo coastal Kenya is the best-kept secret. The dhow captain took us to a sandbank for two hours with no one else. That's the plan." },
    ],
    lodges: [
      { name:"The Majlis", region:"Manda Island · Lamu", note:"Stone suites looking over the channel. The rooftop at sunset is the reason people come back.", img:"https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop" },
      { name:"Almanara Boutique Hotel", region:"Diani Beach", note:"Twelve whitewashed villas, a pool that faces the reef. Quiet, proper, no parties.", img:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop" },
      { name:"Hemingways Watamu", region:"Watamu Marine Park", note:"Old-school East African style, directly above the marine park. Their diving operation is the best on this stretch.", img:"https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop" },
      { name:"Peponi Hotel", region:"Shela · Lamu", note:"Family-run for 50 years. The restaurant has the best calamari on the coast. Always full in January — book early.", img:"https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop" },
      { name:"Baobab Beach Resort", region:"Diani", note:"Larger property, best family setup on the south coast. Pools, kids club, reliable house reef.", img:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop" },
      { name:"Turtle Bay Beach Club", region:"Watamu", note:"PADI 5-star centre, marine conservation programmes. Good for divers who want a base, not just a room.", img:"https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=900&q=80&auto=format&fit=crop",
    ],
    relatedSlugs: ["honeymoon","villa","wellness","safari"],
  },

  wellness: {
    parent: "Slow systems",
    heroRegion: "Slow Kenya · Watamu · Naivasha · Laikipia",
    heroCaption: "Watamu · Reef Hour",
    ctaCopy: "Draft my wellness stay",
    intro: "There are two kinds of wellness trip. The kind where you do yoga at 7am, get a 90-minute massage at 11am, eat in a room made of reclaimed teak, and leave still feeling full. And the kind where you actually change something. Kenya does both — and we'll tell you which one you're booking.",
    why: "Kenyan wellness works because the setting itself does most of the heavy lifting. The sound of the Indian Ocean at 5am, the forest bath in Karura that smells nothing like a spa, the silence at Naivasha on a weekday morning. We place you in properties where the programme supports the place rather than replacing it.",
    whyHeadline: "The setting does the work. The programme supports it.",
    bestMonths: "Jan – Mar · Sep – Nov", groupSize: "1 – 4 travellers", pace: "Slow · programme-led", altitude: "Sea level – 1,900m",
    activities: [
      { title: "Sunrise yoga", desc: "Ocean-facing shalas in Watamu, dawn-light studios in Laikipia. Your mat is already unrolled." },
      { title: "Ayurveda", desc: "Three-to-seven-day programmes at Medina Palms with trained therapists from Kerala and Nairobi." },
      { title: "Forest bath · Karura", desc: "A guided walk through Nairobi's urban forest — shinrin-yoku practice, real trees, zero spa music." },
      { title: "Digital detox bush stay", desc: "Segera Retreat and Ol Jogi don't pretend — zero Wi-Fi, zero signal, complete." },
    ],
    sampleDay: [
      { t: "06:00", title: "Meditation", note: "On the terrace, before the heat. Ten minutes minimum. The ocean cooperates." },
      { t: "07:00", title: "Sunrise yoga", note: "One hour. The instructor brings the class to you — or you to the shala, your call." },
      { t: "08:30", title: "Breakfast", note: "Fresh juice, seasonal fruit, Kenyan porridge with ginger. No buffet, no noise." },
      { t: "10:00", title: "Treatment", note: "Your scheduled Ayurveda session, massage, or hydrotherapy — we book the full programme." },
      { t: "13:00", title: "Lunch", note: "Anti-inflammatory, plant-forward. Good food, not punishing food." },
      { t: "15:00", title: "Free time", note: "Read. Swim. Nap. The point is to stop optimising." },
      { t: "17:00", title: "Evening walk", note: "A slow beach or forest walk as the light changes. Guided or solo." },
      { t: "19:30", title: "Dinner", note: "Small table, candlelight, good wine if you want it. Wellness doesn't mean abstaining." },
    ],
    forWhom: ["Burnout recoverers needing structure","Solo travellers seeking genuine quiet","Couples where one partner needs convincing","Anyone who wants the retreat without the hard sell"],
    notForWhom: ["Party energy seekers","Travellers who hate structure","Those who need entertainment every evening","Fitness performance travellers (that's a different track)"],
    practical: [["Visa","eVisa online · 72h"],["Vaccine","Yellow fever cert."],["Currency","USD · KES"],["Plug","Type G · UK style"],["Connectivity","Intentionally limited at key properties"],["Medical","Pre-arrival health form at some retreats"]],
    pack: ["Light, breathable linens","A journal — you'll use it","Swimwear for pool and ocean","Comfortable walking shoes","Personal supplements if your programme requires them","Leave work laptop at home — seriously"],
    honest: [["Some retreats overpromise","We vet every programme we send clients to. If a property says 'Ayurveda' and means a one-hour back rub, we don't list it."],["April–May rains affect coastal properties","The humidity and intermittent rain can clash with an outdoor programme. We steer you to that window only if your dates are fixed."],["Digital detox is not for everyone","If you've got live projects or kids in school exams, the total-silence properties will stress you out. We'll match the right level."],["It takes three days to land","Don't expect the reset to happen on day one. We build in transition time. That's why we recommend minimum five nights."]],
    quotes: [
      { who: "Rania · solo · 2025", body: "I came off a nine-month product launch. By day three I'd stopped checking my phone out of habit. That had never happened before." },
      { who: "Yuki & Mia · couple · 2025", body: "We'd done Bali twice. Kenya wellness is completely different — the bush setting makes the whole thing land differently." },
      { who: "James · director · 2024", body: "The Segera retreat was four days with zero phone signal. My team survived. I came back a different person." },
    ],
    lodges: [
      { name:"Medina Palms", region:"Watamu", note:"Ayurveda practitioners from Kerala on-site. The programme is real, not spa-menu wellness.", img:"https://images.unsplash.com/photo-1545389336-cf090694435e?w=900&q=80&auto=format&fit=crop" },
      { name:"Segera Retreat", region:"Laikipia Plateau", note:"Art, wildlife, and genuine silence. The spa is secondary to the landscape.", img:"https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=80&auto=format&fit=crop" },
      { name:"Enashipai Resort", region:"Lake Naivasha", note:"Rift Valley setting, proper spa, family-friendly. The lake walk at dawn is the best treatment on the menu.", img:"https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=900&q=80&auto=format&fit=crop" },
      { name:"Sasaab", region:"Samburu", note:"Bush wellness done properly — a pool overlooking the riverbed, yoga at altitude, Maasai-style architecture.", img:"https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop" },
      { name:"Ol Jogi", region:"Laikipia", note:"Private conservancy, full detox available. The silence here is different from anywhere else in Kenya.", img:"https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=900&q=80&auto=format&fit=crop" },
      { name:"Hemingways Nairobi", region:"Karen · Nairobi", note:"The urban option — rooftop spa, good gym, one of the best dining rooms in the city for post-retreat reentry.", img:"https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=900&q=80&auto=format&fit=crop" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1545389336-cf090694435e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551632811-561732d1e306?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop",
    ],
    relatedSlugs: ["beach","honeymoon","villa","safari"],
  },

  honeymoon: {
    parent: "For two",
    heroRegion: "Romance · Mara · Lamu · Samburu",
    heroCaption: "Lamu · Stone House",
    ctaCopy: "Draft our honeymoon",
    intro: "The classic Kenya honeymoon exists for a reason: three nights in the Mara, a bush flight north, a stone house in Lamu for four nights, and the most romantic handover in travel — from savannah to Indian Ocean without a single shared road. We've refined this arc for eight years and we still believe it's the best honeymoon in Africa.",
    why: "The Mara does something to couples that's hard to describe. It's the shared language of a dawn drive, the silence when the vehicle stops, the long lunch with nowhere to be. Then Lamu — slow, Swahili, no cars, no noise. We time the transfer, block the rooms nobody else knows about, and brief both properties on why you're there.",
    whyHeadline: "The Mara, a bush flight, a stone house. In that order.",
    bestMonths: "Jul – Oct · Dec – Jan", groupSize: "2 travellers", pace: "Unhurried · private", altitude: "Variable — sea to 1,800m",
    activities: [
      { title: "Private bush flight", desc: "No shared planes on the classic arc. Your twin Cessna, your schedule, no strangers." },
      { title: "Sunset dhow · Lamu", desc: "A traditional dhow, your captain, cold drinks, the channel turning orange. We book it for the second evening." },
      { title: "In-tent spa", desc: "Your lodge brings the massage table to you. Not a room — your own tent or veranda, looking into the bush." },
      { title: "Private game drive", desc: "Your vehicle, your guide, from the first morning to the last. No sharing, no compromise." },
    ],
    sampleDay: [
      { t: "05:45", title: "Private wake-up", note: "Coffee and rusks at your tent. The camp is quiet — it's just you and the morning." },
      { t: "06:30", title: "Game drive", note: "Your guide has been out since 5am tracking. The leopard was spotted twenty minutes ago." },
      { t: "09:30", title: "Bush breakfast", note: "A table set in the field. The guides carry the eggs in a cool box. It's absurdly good." },
      { t: "12:00", title: "Back to camp", note: "The afternoon belongs to you. Pool, tent, book. The bush quietens at noon." },
      { t: "15:00", title: "In-camp spa", note: "Couples massage on the veranda. The masseuse is on-site. Pre-booked." },
      { t: "17:00", title: "Sundowner drive", note: "Out for the golden light. This is the hour. Long, slow, nowhere else to be." },
      { t: "19:30", title: "Private dinner", note: "Table set by the fire, outside your tent. The team has been briefed. It's yours." },
      { t: "21:00", title: "Campfire", note: "The sky out here doesn't look real. Sit in it for a while." },
    ],
    forWhom: ["New couples and honeymooners","Anniversary and milestone trips","Couples who've done Europe and want the next level","Those who want luxury without performance"],
    notForWhom: ["Groups — this arc doesn't scale","Anyone on a strict budget (we have a budget range for a reason)","Travellers who want nightlife","Those who need to be connected at all times"],
    practical: [["Visa","eVisa online · 72h"],["Vaccine","Yellow fever cert."],["Currency","USD/KES — we brief fully"],["Plug","Type G · UK style"],["Connectivity","Camp = limited · Lamu = minimal by design"],["Flights","We book all domestic, fully coordinated"]],
    pack: ["One smart outfit for the Lamu supper club","Light merino layers for early Mara mornings","A real camera — your phone will do the rest","Minimal luggage — bush flights have strict weight limits","Something white for the Lamu rooftop","Leave the heels — the alleys of Lamu Old Town are cobblestoned"],
    honest: [["Budget matters here","The honeymooner price gap between 'nice' and 'private' is real. We'll give you the exact number for what you want. No surprises."],["Lamu in April is wet","The north coast rains April to May. We'll steer you away or adjust the arc entirely."],["The migration window is competitive","Late July to October is when everyone wants the Mara. Book six months out minimum for peak camps."],["We'll ask about your relationship","Not to be nosy. To brief the camps correctly. A three-month couple gets a different experience than a seven-year one."]],
    quotes: [
      { who: "Ines & Marco · 2025", body: "The moment our bush flight landed in Lamu and the donkey was the first thing we saw — that's the image from our entire honeymoon. Better than any hotel lobby in the world." },
      { who: "Sarah & James · 2025", body: "We'd been together twelve years. Kenya brought back something we didn't know we'd lost. Ten days, zero arguments, one sunset we'll never stop talking about." },
      { who: "Priya & Dev · anniversary · 2024", body: "The in-tent dinner on the last Mara night. There were candles in the sand around our table. I cried. He cried. The guide pretended not to notice." },
    ],
    lodges: [
      { name:"Sala's Camp", region:"Sand River · Mara", note:"Six tents on the migration crossing. The most intimate camp in the Mara. Candlelit dinners outside.", img:"https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop" },
      { name:"Angama Mara", region:"Mara Triangle", note:"Two suites at the end of the deck — uninterrupted escarpment views and the best service in Kenya.", img:"https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop" },
      { name:"Peponi Hotel", region:"Shela · Lamu", note:"Family-run for 50 years. The Lamu classic. Ask for room 12. The channel view at sunrise is the deal.", img:"https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop" },
      { name:"The Majlis", region:"Manda Island · Lamu", note:"Stone suites above the channel. The most private swimming pool in East Africa.", img:"https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop" },
      { name:"Sasaab", region:"Samburu", note:"Alternative to Lamu for couples wanting a third location. Pool, bush, river views. Very romantic, very quiet.", img:"https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop" },
      { name:"Ol Donyo Lodge", region:"Chyulu Hills", note:"Kilimanjaro on the horizon from the bath. The star beds are exactly what they sound like — a bed on an open platform above the bush.", img:"https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=900&q=80&auto=format&fit=crop",
    ],
    relatedSlugs: ["safari","beach","villa","wellness"],
  },

  nomad: {
    parent: "Long-stay",
    heroRegion: "Long-stay Kenya · Nairobi · Diani · Watamu",
    heroCaption: "Nairobi · Karen Home",
    ctaCopy: "Plan my long stay",
    intro: "Kenya runs on UTC+3, has four international fibre cables landing at Mombasa, costs a third of London for the equivalent quality of life, and has a startup culture in Nairobi that punches well above its global profile. If you're remote and serious about a long stay, this is the most underrated destination on earth.",
    why: "The math works out fast: a vetted villa in Karen with cook, cleaner and broadband costs less than a studio in Shoreditch. But Kenya isn't a commodity destination — it rewards effort. We handle the residency paperwork, find the co-working community that actually suits your work style, and make the logistics invisible so you can just get on with it.",
    whyHeadline: "The fibre is there. The cost makes sense. The life is better.",
    bestMonths: "Jan – Mar · Jun – Oct", groupSize: "1 – 4 people", pace: "Work-from-home rhythm", altitude: "1,700m · Nairobi / sea level · coast",
    activities: [
      { title: "Co-working setup", desc: "iHub, Nairobi Garage, Workstyle Afrika — we match your work culture, not just your broadband spec." },
      { title: "Staffed villa", desc: "A cook, a cleaner, a watchman. Vetted by us, employed directly by you. Weekly cost comparable to a London restaurant tab." },
      { title: "SIM + residency brief", desc: "Safaricom line activated, residency permit explained, and a local accountant introduction if you need invoicing." },
      { title: "Weekend safari block", desc: "Your base city, a bush drive at the weekend. We block-book a conservancy so you have a standing escape." },
    ],
    sampleDay: [
      { t: "06:30", title: "Morning run", note: "Karura Forest in Nairobi. 1,065 hectares, no cars, free entry. Better than any gym." },
      { t: "08:00", title: "Breakfast at home", note: "Your cook has been in since 7:30. Fresh mandazi, eggs, Kenyan tea. The table is set." },
      { t: "09:00", title: "Work", note: "From home or the co-working space. 200Mbps verified. Backup Safaricom hotspot if you need it." },
      { t: "13:00", title: "Lunch break", note: "A local canteen in Karen or a proper sit-down with a colleague. The food is better and cheaper than you think." },
      { t: "15:00", title: "Work, continued", note: "UTC+3 keeps you ahead of London, aligned with Dubai, two hours off New York. It works." },
      { t: "18:00", title: "Evening", note: "Rooftop bar in Lavington, a dinner at Cultiva, a drive past the giraffes near the centre. Nairobi has a good evening." },
      { t: "21:00", title: "Home", note: "Your own kitchen, your own table, your cook's leftovers in the fridge. It's not a hotel." },
      { t: "Friday", title: "Weekend starts early", note: "Car booked, camp confirmed. The Mara or the Crater for the weekend. Back Monday morning." },
    ],
    forWhom: ["Remote workers on month-plus stays","Founders and operators between fundraising rounds","Sabbatical-takers wanting substance","Anyone priced out of Bali but unwilling to settle"],
    notForWhom: ["Short-trip tourists — this is the wrong product","Anyone needing US or EU timezone alignment (it can work but needs planning)","Those who need urban stimulation around the clock","Travellers who won't learn two phrases of Swahili"],
    practical: [["Visa","Visitor pass → E-Resident permit for 90+ days"],["Fibre","Safaricom Home Fibre · 100–400 Mbps in Karen, Westlands, Kilimani"],["Banking","M-Pesa opens in 10 minutes · international cards work fine"],["Healthcare","MP Shah, Aga Khan — quality private care"],["Security","Gated estates in Karen, Runda, Lavington — standard"],["Tax","Consult your home country rules — Kenya has a DTT with many nations"]],
    pack: ["Your proper work setup — monitor if you need one","Two power adaptors (Type G / UK) and a UPS for power dips","Your full wardrobe — you'll be here a while","One warm layer for the Nairobi evenings","VPN subscription","The coffee is exceptional. Leave room in your bag on the way home."],
    honest: [["Traffic is real","Nairobi's jams are legendary. We'll map your co-working to your accommodation. Don't live in Westlands and work in Karen."],["Power cuts happen","Usually short, usually compensated by a generator at better properties. We check before we book."],["Security is contextual","Karen, Runda, Lavington — different story from parts of Eastleigh at midnight. We brief you properly, not scare you."],["Kenya will get under your skin","Most people plan a month and stay three. Budget for it."]],
    quotes: [
      { who: "Rafa · product designer · 2025", body: "Six weeks in Karen. Better broadband than my London flat, a cook who learned my breakfast order on day two, and I went on safari three weekends. When do I go back?" },
      { who: "Lena · founder · 2025", body: "We had a team sprint in Nairobi in August. Seven people, a villa in Karen, three days of work and one weekend in the Mara. Best team offsite we've ever done." },
      { who: "Tom · writer · 2024", body: "The mornings in Karura Forest gave me the first manuscript chapter I'd been stuck on for three months. Something about the altitude and the trees." },
    ],
    lodges: [
      { name:"Karen long-stay villas", region:"Karen · Nairobi", note:"Six-to-twelve month vetted houses with full staff. Green suburb, good schools nearby, easy Ngong Road access.", img:"https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=900&q=80&auto=format&fit=crop" },
      { name:"Diani beachfront homes", region:"Diani Beach", note:"Month-rate properties on or near the beach. Fibre available from Safaricom. Co-working in Diani town.", img:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop" },
      { name:"Watamu studios", region:"Watamu", note:"Smaller, more affordable. Closest to the beach, marine park access, quieter pace.", img:"https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop" },
      { name:"Westlands apartments", region:"Westlands · Nairobi", note:"Urban option — walkable to Sarit Centre, Sankara, co-working community. Higher urban energy.", img:"https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=900&q=80&auto=format&fit=crop" },
      { name:"Naivasha weekend base", region:"Lake Naivasha", note:"Two hours from Nairobi. A weekend house by the lake. Hippos in the garden, flamingos in the morning.", img:"https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=900&q=80&auto=format&fit=crop" },
      { name:"Lamu island studios", region:"Shela · Lamu", note:"No cars, no noise, incredible creative output. Not for the month — for the sprint. We book fortnightly.", img:"https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611348586804-61bf6c080437?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop",
    ],
    relatedSlugs: ["villa","wellness","beach","safari"],
  },

  family: {
    parent: "With kids",
    heroRegion: "Family Kenya · Nairobi · Mara · Watamu",
    heroCaption: "Karen · Giraffe Centre",
    ctaCopy: "Plan our family trip",
    intro: "We've sent 240+ families to Kenya. We know the camps where the kids get their own game drive vehicle. We know the lodge with a pool and a doctor on call. We know the Watamu stretch where a seven-year-old can snorkel safely. And we know what breaks when it goes wrong — which is the thing we prevent.",
    why: "Family travel in Kenya works because the country genuinely welcomes kids — and because we've done the logistics properly so the parents can be present. We map the nap windows, locate the pools, brief the camps, and make sure the pediatrician number is in your phone before you land.",
    whyHeadline: "Your kids remember the giraffe. You remember not carrying a single bag.",
    bestMonths: "Jul – Oct · Dec – Jan", groupSize: "Family of 3–8", pace: "Child-friendly · pools required", altitude: "Variable",
    activities: [
      { title: "Giraffe Manor breakfast", desc: "The Rothschild giraffes lean in at the window. It's the most requested single experience in Kenya. We get you the table." },
      { title: "Family game drive", desc: "Your own vehicle, a guide who's briefed on the kids, and a stop for hot chocolate at the kopje." },
      { title: "Kids club · Watamu", desc: "Hemingways and Turtle Bay run supervised programmes. Three hours of marine education and snorkeling. Parents: breathe." },
      { title: "Elephant Orphanage · Nairobi", desc: "The DSWT orphanage in Nairobi — baby elephants at 11am, every day. Forty-five minutes of unmatchable delight." },
    ],
    sampleDay: [
      { t: "06:30", title: "Early risers", note: "Kids are up. Game drive leaves at seven — they'll be thrilled. Breakfast is available from 6am." },
      { t: "07:00", title: "Family game drive", note: "Your vehicle, your guide, your pace. The binoculars are child-sized. The radios are switched to giraffe frequency." },
      { t: "10:00", title: "Bush breakfast", note: "Eggs and toast by the river. A junior ranger talk from your guide on the way back." },
      { t: "12:00", title: "Pool time", note: "Every camp we book has a pool. Kids in, parents beside it. This is the plan." },
      { t: "14:00", title: "Camp siesta", note: "The little ones nap. The parents read. The camp is quiet. This is why we book these camps." },
      { t: "16:00", title: "Afternoon activity", note: "Depending on the day: guided nature walk, campfire cooking class, or a trip to the Mara River." },
      { t: "18:00", title: "Sundowner (kid-friendly)", note: "Juice for the small ones, gin for the parents. The guide tells the evening story." },
      { t: "20:00", title: "Dinner", note: "Early family dinner, then the kids are escorted to bed by the camp team. Parents: another hour." },
    ],
    forWhom: ["Families with kids aged 5–16","Parents who want their kids to have the defining trip of childhood","Multi-generational groups (grandparents welcome)","First-time Kenya families"],
    notForWhom: ["Infants under 4 — most camps have a minimum age","Families who need theme parks and flat ground","Groups who can't agree on pace","Anyone who needs everything identical to home"],
    practical: [["Visa","eVisa · children included on adult form under 16"],["Vaccine","Yellow fever cert · consult paediatrician for under-5s"],["Medical","Pediatrician on call organised before arrival"],["Malaria","Prophylactics essential · we advise on regimen for kids"],["Luggage","Bush flight limits strict — we brief on packing per camp"],["Connectivity","Camps have emergency satellite — we share the number"]],
    pack: ["Layers — mornings are cold even in high season","Closed-toe shoes for all game drives","Kids' binoculars — the gift that pays for itself","Insect repellent · DEET 20–30% for under-12s","A few favourite snacks from home for the first night","A small field guide — kids love the animal name game"],
    honest: [["Some camps won't take under-5s","We tell you upfront. There are alternatives that do, and they're often better for small kids anyway."],["Game drives are early","5:30am starts. Kids are usually thrilled for the first two days. By day three we build in a rest morning."],["The migration is not guaranteed","We explain this clearly and set expectations before you land. The bush always delivers something — just not always the thing on the poster."],["It's physically big","Distances between experiences are real. Bush flights are non-negotiable for families — we don't do 8-hour overland with kids."]],
    quotes: [
      { who: "The Osei family · 5 · 2025", body: "Our 8-year-old told his school he saw a cheetah kill. He's the most popular kid in class. Our 5-year-old's first question every morning was 'what animal today?' This is the trip." },
      { who: "Charlotte · solo mum · 3 kids · 2025", body: "I was terrified of doing this alone with three kids. By day two I was relaxed because the camp team had absorbed the logistics. The pediatrician on call was the detail that made me book." },
      { who: "The Nakamura family · 4 · 2024", body: "My teenagers said they'd prefer Ibiza. By the end of day one in the Mara they were asking about coming back. Kenya wins the argument every time." },
    ],
    lodges: [
      { name:"Giraffe Manor", region:"Langata · Nairobi", note:"The Rothschild giraffes at breakfast. You know this one. The booking is the hard part — we get it.", img:"/giraffe-manor.jpg" },
      { name:"Hemingways Watamu", region:"Watamu Marine Park", note:"Kids club, house reef, pool, supervised snorkeling. Family travel doesn't get easier.", img:"https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop" },
      { name:"Mara Bushtops", region:"Masai Mara", note:"Family suites, a pool with a view of the plains, kids menu on the full restaurant. One of the best family camps in the Mara.", img:"https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop" },
      { name:"Sanctuary Olonana", region:"Mara North Conservancy", note:"Tented suites on the river. Family suites connect. The hippos at night are the children's favourite audio.", img:"https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop" },
      { name:"Porini Amboseli Camp", region:"Selenkay Conservancy", note:"Excellent family value. Kilimanjaro mornings, elephants at the waterhole, community-run walking programme.", img:"https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop" },
      { name:"Neptune Beach Resort", region:"Diani Beach", note:"Family resort on the best south coast beach. Pools, watersports, kids club, kids-menu standard.", img:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop" },
    ],
    gallery: [
      "/giraffe-manor.jpg",
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=900&q=80&auto=format&fit=crop",
    ],
    relatedSlugs: ["safari","beach","wellness","honeymoon"],
  },

  villa: {
    parent: "Whole-house",
    heroRegion: "Private Kenya · Lamu · Diani · Karen",
    heroCaption: "Lamu · Forodhani House",
    ctaCopy: "Find my villa",
    intro: "The best accommodation in Kenya isn't a hotel. It's a six-bed stone house in Lamu Old Town where the rooftop has a view over the entire harbour, a full cook, a laundry woman, and a dhow captain on call. Or a cliff-side villa in Watamu where the pool hangs above the marine park and there's no one else in the building. We hold relationships with forty private houses.",
    why: "Private villa travel in Kenya works because the staff are real — not hired for the season, but attached to the house long-term. The cook knows the market. The caretaker knows the neighbours. The house has a personality. When you're staying for a week with four friends or a multi-generational group, this is a fundamentally different experience from a hotel room.",
    whyHeadline: "The cook knows the market. The house has a personality.",
    bestMonths: "Dec – Mar · Jul – Oct", groupSize: "4 – 14 travellers", pace: "House rhythm — entirely yours", altitude: "Sea level – 1,700m",
    activities: [
      { title: "Full staff management", desc: "We brief the cook, house team and driver before you arrive. Your dietary requirements are already in the kitchen." },
      { title: "Private dhow", desc: "A dedicated dhow on call in Lamu — your captain, your timetable, sunset when you want it." },
      { title: "Chef market run", desc: "The cook goes to the market at 7am. You choose the menu at breakfast. The fish was in the ocean that morning." },
      { title: "House vehicle + driver", desc: "A dedicated driver and vehicle for the duration. No transfers, no waiting, no shared shuttles." },
    ],
    sampleDay: [
      { t: "07:00", title: "Morning", note: "The cook has been in since 6:30. Coffee is ready. The table is set how you asked yesterday." },
      { t: "08:00", title: "Breakfast", note: "Eggs your way, fresh fruit from the market, Kenyan tea. The whole house at one table." },
      { t: "09:30", title: "Beach or pool", note: "Your choice. The driver is on standby. The dhow captain is ready by 10 if you want the morning sail." },
      { t: "12:30", title: "Lunch at home", note: "The cook prepared something you actually asked for. Not a menu — your conversation with them this morning." },
      { t: "14:00", title: "Afternoon", note: "A nap, a game, a walk. The house is yours. Nobody is on a programme." },
      { t: "16:00", title: "Excursion", note: "The village, the snorkel spot, the fort. The driver knows where everything is and knows how to park." },
      { t: "19:00", title: "Sundowner at home", note: "The rooftop or the terrace. Drinks from the fridge you stocked together. The house at golden hour." },
      { t: "20:30", title: "Dinner", note: "Three courses at your table. The cook is a professional. Tonight it's Swahili biryani." },
    ],
    forWhom: ["Groups of 4–14 friends or family","Multi-generational extended family trips","Friend group celebrations (40th, 50th birthdays)","Couples who want absolute privacy at scale"],
    notForWhom: ["Solo travellers — the economics don't work","Couples wanting hotel-level service and flexibility","Anyone expecting a managed resort experience","Those who need daily room-cleaning at a specific time"],
    practical: [["Visa","eVisa · one per person"],["Staffing","Full-time cook, cleaner, askari (night guard) standard"],["Grocery","We arrange pre-arrival stock. The cook handles daily fresh market"],["Driver","Dedicated vehicle for the house throughout stay"],["Connectivity","Varies by property — we verify fibre before booking"],["Luggage","No weight limits — it's your house, bring what you need"]],
    pack: ["Everything you need for a house stay — this isn't hotel packing","A good playlist — you own the speaker","One smart outfit for the Lamu supper club","Reef shoes for the Watamu coast houses","Wine, gin, whatever you'd bring to a house party — the airport has decent options","A household tip envelope — we'll advise the amount"],
    honest: [["Not every villa is as photographed","We visit before we list. But properties evolve. If a house is off our list we'll tell you why."],["Staff dynamics take a day","The cook needs your food preferences. The driver needs to know your pace. Day one is an orientation — build in one easy day at the start."],["Group dynamics apply","In a shared house, disagreements happen. We scope-check group size and relationships before recommending a house."],["Lamu logistics are real","No cars means porters. For villa arrivals in Lamu Old Town, we organise the porter team, the boat transfer, the timing. All handled."]],
    quotes: [
      { who: "The Bergström group · 9 · 2025", body: "Nine of us, four days in the Forodhani House. The cook made the best meal of the holiday every evening. The rooftop on the last night was the send-off we needed." },
      { who: "Isabelle · 50th birthday · 2025", body: "I brought twelve friends to a Diani cliff villa. The staff already knew everyone's name by the second morning. It felt like a family home we'd had for years." },
      { who: "Mark & family · 3 generations · 2024", body: "Grandparents, parents, and four kids in a Karen house. The cook made the grandparents' Kenyan tea the way they remembered it from their posting in 1978. That moment." },
    ],
    lodges: [
      { name:"Forodhani House", region:"Lamu Old Town", note:"Six bedrooms in a restored 19th-century Swahili mansion. Rooftop overlooking the harbour. Full cook and house team.", img:"https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop" },
      { name:"Alfajiri Villas", region:"Diani Beach", note:"Three clifftop villas above the reef. The pool looks directly onto the Indian Ocean. Fully staffed, private beach access.", img:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop" },
      { name:"Robinson Island", region:"Lamu Archipelago", note:"A private island with two cottages. Accessible by boat only. Absolute seclusion.", img:"https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop" },
      { name:"Karen villas", region:"Karen · Nairobi", note:"Garden estates in Nairobi's green suburb. Five to eight bedrooms, full staff, country club access on request.", img:"https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=900&q=80&auto=format&fit=crop" },
      { name:"Watamu cliff houses", region:"Watamu", note:"Three properties above the marine park. Pool, reef access, and a house cook who knows the fish market personally.", img:"https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop" },
      { name:"Kipungani Explorer", region:"Lamu South Coast", note:"Mangrove setting, dhow on call, six bandas with full service. One of the most peaceful addresses in Kenya.", img:"https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop",
    ],
    relatedSlugs: ["honeymoon","beach","nomad","family"],
  },

  photo: {
    parent: "Right light",
    heroRegion: "Right Light · Mara · Samburu · Lamu",
    heroCaption: "Mara · Golden Hour Drive",
    ctaCopy: "Plan my photography trip",
    intro: "We built this track with two former National Geographic expedition guides — one who has spent 22 years in the Mara, one who knows the Samburu riverbed hide positions better than anyone alive. The result is a photography itinerary that treats light and position as the primary variables, not the camp breakfast time.",
    why: "Kenya's photography window is the most democratic on the continent. You don't need a 600mm lens to get the shot that makes people ask 'where was that taken?'. The Mara's open savannah gives you proximity and context simultaneously. The Samburu's dusty red palette is unlike anything in East Africa. And the light — particularly July to October — is the kind that photographers spend careers chasing.",
    whyHeadline: "The light is the itinerary. Everything else is logistics.",
    bestMonths: "Jul – Oct · Jan – Feb", groupSize: "1 – 6 photographers", pace: "Light-chasing · very early starts", altitude: "1,500 – 2,000m",
    activities: [
      { title: "Specialist photo guide", desc: "A guide trained in photography positioning — they know which angle, which light, which vehicle orientation. Not a game guide who tolerates a camera." },
      { title: "Custom vehicle mounts", desc: "Bean bags, gimbal mounts, and beanbag window rests fitted in your vehicle from day one. No improvising." },
      { title: "Drive-up hides", desc: "Fixed and mobile hides at waterholes in Samburu and Laikipia — wide-angle shots that would otherwise require a blind and three days of patience." },
      { title: "On-site editing workflow", desc: "Camp editing suites at Mara Plains and Saruni Samburu — monitor, card reader, dual backup drives. The workflow is part of the daily programme." },
    ],
    sampleDay: [
      { t: "05:00", title: "Pre-dawn out", note: "Earlier than any other track. The cats are still moving in the last dark. Your guide has the radio on." },
      { t: "06:15", title: "Golden hour", note: "The magic window. Your guide knows exactly where the light falls on the ridge. The vehicle is already positioned." },
      { t: "08:30", title: "Bush breakfast + review", note: "Back to camp, breakfast, quick edit review. What did we get? What do we need today's afternoon for?" },
      { t: "10:00", title: "Waterhole hide", note: "Two hours at the fixed hide. Elephant, buffalo, warthog. Your guide has the radio off — silence required." },
      { t: "12:30", title: "Edit session", note: "Camp editing suite. Your guide sits with you and briefs the afternoon positions based on this morning's missed shots." },
      { t: "15:30", title: "Out for golden afternoon", note: "The second magic window. Position briefed at lunch. Today it's the kopje with the cheetah that's been sighted three days running." },
      { t: "18:45", title: "Sunset and blue hour", note: "The Mara sky at blue hour is undershot by most visitors. We stay out until full dark, then transfer with headlights." },
      { t: "20:30", title: "Backup and brief", note: "Cards backed up to two drives. Tomorrow's programme set. You eat knowing the morning is already planned." },
    ],
    forWhom: ["Serious amateurs with a full-frame camera","Professional photographers on assignment","Wildlife and travel magazine contributors","Anyone who views the camera as the point of the trip, not the accessory"],
    notForWhom: ["Travellers who want the photo but not the process","Those who can't do pre-5am starts","Casual snappers — this is an investment track, not a camera-friendly general safari","Groups with mixed agendas — photography pace is incompatible with social safari"],
    practical: [["Visa","eVisa online · 72h"],["Vaccine","Yellow fever cert."],["Currency","USD · KES"],["Equipment","Declare camera gear at customs — no issue if declared"],["Bush flights","Strict 15kg hold limit — we help you pare the kit list"],["Connectivity","Camp editing suites have power · no public WiFi in bush"]],
    pack: ["Your longest lens — 400mm+ preferred for wildlife","A second body — dust and dew are real","Bean bags — we provide but your own is better","Sensor cleaning kit · the dust in Samburu is relentless","A hard drive — cards fill faster than you expect","A colour calibration card for the editing session"],
    honest: [["The migration sighting is not guaranteed","We position you for the best odds. The wildebeest cross when they choose. We've had clients wait six days and miss it. We've also had them see it on day one."],["Pre-dawn departures are non-negotiable","If you can't do 4:30am, this isn't the right track for you. The light is the point. The light is early."],["Dust is everywhere in Samburu","Your sensor will need cleaning. Your camera bag will need sealing. Your clothes will be orange by day two."],["The best positions require the guide's judgement","We give you the guide, not the GPS. Trust the human who has been doing this since before your longest lens was manufactured."]],
    quotes: [
      { who: "Maya · documentary photographer · 2025", body: "The hide at Ol Pejeta gave me an elephant portrait at 18mm. No zoom, no distance — a full-frame face looking directly into my lens. That image is in the collection." },
      { who: "Kenji · travel photographer · 2024", body: "I've shot India, Patagonia, Iceland. The Mara in September at 5:30am with a specialist guide and a private vehicle is in a different category." },
      { who: "Sarah · wildlife biologist + photographer · 2024", body: "The editing suite at Mara Plains changed everything. Reviewing the morning's work with the guide and adjusting the afternoon's plan — that's a workflow, not a holiday." },
    ],
    lodges: [
      { name:"Mara Plains Camp", region:"Olare Motorogi · Mara", note:"Seven tents on raised decks, specialist photo vehicles fitted standard. The in-camp editing room is a genuine darkroom replacement.", img:"https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop" },
      { name:"Saruni Samburu", region:"Kalama Conservancy", note:"Six lodges on a rocky kopje. The waterhole hides are 200 metres from the main camp. Dust, colour, silence.", img:"https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop" },
      { name:"Angama Mara", region:"Mara Triangle", note:"The Oloololo escarpment view gives you a photography angle no other Mara camp has. The glass-front tent frames the plain.", img:"https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop" },
      { name:"Lamu House", region:"Shela · Lamu", note:"Three-bedroom house with rooftop studio space. Dhow photography on the channel, street portrait sessions in Old Town.", img:"https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop" },
      { name:"Ol Pejeta Conservancy stays", region:"Laikipia", note:"Rhino, chimpanzee sanctuary, and the highest density of wildlife in Laikipia. Fixed hides, walking photo safaris.", img:"https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop" },
      { name:"Sirikoi", region:"Lewa Conservancy", note:"Four cottages, owner-run. Horses available for a different camera angle. Rhino and grevy's zebra in the conservancy.", img:"https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=900&q=80&auto=format&fit=crop" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551632811-561732d1e306?w=900&q=80&auto=format&fit=crop",
    ],
    relatedSlugs: ["safari","honeymoon","wellness","beach"],
  },

  "bucket-list": {
    parent: "Giraffe Manor & beyond",
    heroRegion: "Bucket List Kenya · Nairobi · Mara · Laikipia",
    heroCaption: "Langata · Giraffe Manor",
    ctaCopy: "Build my bucket list trip",
    intro: "Some experiences in Kenya have earned the word iconic honestly. The Rothschild giraffes leaning into the dining room at Giraffe Manor. The dawn light over the Mara from a balloon at 1,000 feet. The baby elephants at the DSWT orphanage, forty minutes from Nairobi. We've spent years building the relationships that get you these moments — not the standard version, but the version that stays with you.",
    why: "The difference between doing Giraffe Manor and doing it properly is the room, the timing, and the brief. We get you the ground-floor corner suite where the giraffes press their noses to the glass at breakfast. We make sure the Mara balloon is a private flight, not a shared one. We tell the elephant orphanage team that you're coming — and they introduce you by name to the baby they've had the longest.",
    whyHeadline: "The iconic moments are real. Getting them right is the work.",
    bestMonths: "Jun – Oct · Dec – Jan", groupSize: "2 – 8 travellers", pace: "Curated · unhurried", altitude: "1,700m Nairobi · 1,500m Mara",
    activities: [
      { title: "Giraffe Manor breakfast", desc: "The Rothschild giraffes arrive at 8am. We book the ground-floor suite where they press against the window. There is no other experience quite like this." },
      { title: "Hot-air balloon · Mara", desc: "Private basket at dawn, one hour above the plains. Champagne breakfast in the bush after landing. We book the pilot, not the operator." },
      { title: "DSWT Elephant Orphanage", desc: "The David Sheldrick Wildlife Trust opens its Nairobi orphanage at 11am daily. Baby elephants in a muddy pen, 40 minutes from the city centre. A perfect second morning." },
      { title: "Ol Pejeta rhino conservancy", desc: "Home to the last two northern white rhinos on earth. Walking with a ranger to within twenty metres is a different experience from a vehicle." },
    ],
    sampleDay: [
      { t: "06:45", title: "Giraffe Manor morning", note: "The giraffes arrive for their feed before 8am. You're in the ground-floor room. They come to the window." },
      { t: "08:00", title: "Breakfast", note: "The full dining room, giraffes present. Other guests look at their phones. You don't." },
      { t: "10:00", title: "Transfer to Nairobi", note: "Elephant Orphanage opens at 11am. Your driver has been briefed on timing." },
      { t: "11:00", title: "DSWT Orphanage", note: "Baby elephants in the mud. Named, known, each with a keeper. Forty-five minutes that no one forgets." },
      { t: "13:30", title: "Lunch in Karen", note: "Talisman, Cultiva, or the hotel. A proper sit-down before the afternoon drive." },
      { t: "16:00", title: "Bush flight to the Mara", note: "Afternoon charter. Your guide meets you at the airstrip. Camp is fifteen minutes." },
      { t: "18:30", title: "Sundowner", note: "First evening in the Mara. The balloon briefing happens here — 4:30am tomorrow." },
      { t: "04:30", title: "Balloon morning", note: "Your guide drives you to the launch point. The balloon is yours. Dawn begins at 5:45 above the plains." },
    ],
    forWhom: ["First-time Kenya visitors who want the marquee moments","Anniversary and milestone travellers","Parents who want the trip their children will never forget","Anyone who's said 'I've always wanted to do Giraffe Manor'"],
    notForWhom: ["Purists who find iconic experiences overrated","Deep bush seekers — this has Nairobi built in","Those on a strict budget (Giraffe Manor is priced as a bucket list property)","Anyone who needs everything to be undiscovered"],
    practical: [["Visa","eVisa online · 72h"],["Giraffe Manor","Book 6–12 months out in peak season — we hold allocations"],["Balloon","Weather-dependent · we have a backup plan"],["Currency","USD · KES on arrival"],["Plug","Type G · UK style"],["Medical","Nairobi has top-tier private hospitals — useful to know"]],
    pack: ["One smart outfit for Giraffe Manor dinner — it's a house, not a restaurant","Neutral layers for the Mara and balloon (cold at 4:30am, warm by 9am)","A camera — this is the trip where you'll want one","Closed shoes for Ol Pejeta walking","Something for the kids — DSWT sells adoption certificates at the gate","Leave the white clothing — the Nairobi dust is real"],
    honest: [["Giraffe Manor books out fast","We hold preferred allocations but peak school-holiday dates can be 12 months out. Come to us early."],["The balloon is weather-dependent","The Mara gets wind. We book with reputable operators who have professional pilots and a standby plan. We've never had a full cancellation — but we brief you on the possibility."],["Ol Pejeta requires a day","It's four hours from Nairobi. We recommend an overnight at the conservancy rather than a day trip — the morning walking session with the rhinos is the experience, not the drive-through."],["The orphanage is 45 minutes","Any more time than that and it becomes overwhelming — for you and the elephants. We book the visit and the exit at the right moment."]],
    quotes: [
      { who: "Lena & Marc · 25th anniversary · 2025", body: "I've been travelling for 30 years. The giraffe's nose on the glass at breakfast, six inches from my face — nothing I've seen before or since. We extended the stay by two nights." },
      { who: "The Bergström family · 5 · 2025", body: "My daughter is nine. She now tells everyone her best friend is a baby elephant named Naledi. The DSWT adoption certificate is framed in her bedroom." },
      { who: "James · solo · 2024", body: "The balloon pilot turned off the gas burner and we floated in complete silence for four minutes above a lion pride. That silence is what I came for." },
    ],
    lodges: [
      { name:"Giraffe Manor", region:"Langata · Nairobi", note:"Twelve rooms in a 1930s manor house. The Rothschild giraffes arrive at feeding time. We know which room.", img:"/giraffe-manor.jpg" },
      { name:"Angama Mara", region:"Mara Triangle · Nairobi", note:"The balloon launch partner. Glass-fronted tents on the Oloololo escarpment. The best post-balloon champagne breakfast view in Africa.", img:"https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop" },
      { name:"Ol Pejeta Bush Camp", region:"Ol Pejeta Conservancy · Laikipia", note:"Eight tents inside the rhino conservancy. Walking safaris with armed rangers. The last two northern white rhinos are 400 metres from the dining room.", img:"https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop" },
      { name:"Hemingways Nairobi", region:"Karen · Nairobi", note:"The best urban base for the Nairobi experiences. Rooftop bar, excellent service, five minutes from Giraffe Manor.", img:"https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=900&q=80&auto=format&fit=crop" },
      { name:"Sala's Camp", region:"Sand River · Mara", note:"Six tents on the migration crossing — the most intimate camp in the Mara and our preferred balloon-morning base.", img:"https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop" },
      { name:"Ol Donyo Lodge", region:"Chyulu Hills", note:"Star beds above the bush. The bucket list doesn't have to end in Nairobi — Ol Donyo adds the final night under an open sky.", img:"https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=900&q=80&auto=format&fit=crop" },
    ],
    gallery: [
      "/giraffe-manor.jpg",
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop",
      "/single-mother-safari.jpg",
      "https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop",
    ],
    relatedSlugs: ["family","safari","honeymoon","photo"],
  },
};

export type JournalEntry = {
  n: string; kicker: string; title: string; excerpt: string;
  read: string; author: string; date: string; img: string; accent: string;
};

export const JOURNAL_ENTRIES: JournalEntry[] = [
  { n:"01", kicker:"Field notes", title:"Three quiet cafés in Nairobi worth a morning", excerpt:"A founder's apartment-turned-roastery in Lavington, a courtyard in Karen with the best Eggs Selin, and a corner bakery in Kilimani where everyone eventually shows up.", read:"4 min", author:"Selin Tapıcı", date:"Mar · 2026", img:"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop", accent:"red" },
  { n:"02", kicker:"Guide", title:"The boutique stays we send our closest friends to", excerpt:"Twelve houses, camps, and rooms we'd put our own family in. Some you can book direct. Some you can't — that's the whole point of the concierge.", read:"8 min", author:"Selin Tapıcı", date:"Feb · 2026", img:"https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop", accent:"green" },
  { n:"03", kicker:"Safety", title:"What women travelers actually need to know about Kenya", excerpt:"Practical, plain, no scare-quotes. Where to walk alone after dark, where not to, what to wear in Lamu Old Town, and the WhatsApp numbers we keep on speed dial.", read:"11 min", author:"Wanjiku Mwangi", date:"Feb · 2026", img:"https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop", accent:"black" },
  { n:"04", kicker:"Versus", title:"Diani or Watamu — choosing your stretch of coast", excerpt:"Honeymooners ask us this every week. We did the homework: tide times, kid-friendliness, where you can walk to dinner, where you'd better book the driver.", read:"6 min", author:"Hassan Ali", date:"Jan · 2026", img:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop", accent:"red" },
  { n:"05", kicker:"Field notes", title:"A weekend in Iten — running where the world's fastest run", excerpt:"2,400m, red dirt tracks at dawn, 24 Kenyans you've never heard of who could win the Vienna marathon. A two-day visit, slowly.", read:"7 min", author:"Tom O'Neill", date:"Jan · 2026", img:"https://images.pexels.com/photos/2402777/pexels-photo-2402777.jpeg?auto=compress&cs=tinysrgb&w=900", accent:"green" },
  { n:"06", kicker:"Guide", title:"Single-mother safari — how we plan it", excerpt:"The hidden tax of solo travel with kids isn't money — it's logistics. Here's the framework we use to make it feel like a real holiday, not a project.", read:"9 min", author:"Selin Tapıcı", date:"Dec · 2025", img:"/single-mother-safari.jpg", accent:"sand" },
  { n:"07", kicker:"Conversation", title:"Letter from a Maasai guide — twenty years on the plains", excerpt:"James has tracked the same prides through three generations. We sat with him under a fig tree for an afternoon and asked what the bush is teaching him now.", read:"12 min", author:"James ole Kimani", date:"Dec · 2025", img:"https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop", accent:"black" },
  { n:"08", kicker:"Versus", title:"Mara conservancies, ranked the way we'd actually pick", excerpt:"Olare Motorogi vs Naboisho vs Mara North vs Mara Triangle. Vehicle rules, density, off-road, walking allowed, the lot. The cheat-sheet we keep on our desk.", read:"9 min", author:"Selin Tapıcı", date:"Nov · 2025", img:"https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=900&q=80&auto=format&fit=crop", accent:"red" },
  { n:"09", kicker:"Field notes", title:"The dhow boys of Lamu — sunset is at six", excerpt:"How the boats are crewed, how the sails are tied, what to tip, and why the best ones now book up four days out. Plus the captain we always call first.", read:"5 min", author:"Hassan Ali", date:"Nov · 2025", img:"https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop", accent:"green" },
  { n:"10", kicker:"Guide", title:"What it costs · a real Kenya budget, line by line", excerpt:"We tear apart three of our recent itineraries — $9k, $18k, $42k — and show you exactly where the money went. No fluff, no marketing rounding.", read:"10 min", author:"Selin Tapıcı", date:"Oct · 2025", img:"https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=900&q=80&auto=format&fit=crop", accent:"black" },
  { n:"11", kicker:"Safety", title:"Driving in Kenya — when to, when not to, and why we usually do it for you", excerpt:"Self-drive vs hired driver vs scheduled flights. The honest cost-of-time and cost-of-stress breakdown, with the one stretch of road we still drive ourselves.", read:"7 min", author:"Tom O'Neill", date:"Oct · 2025", img:"https://images.unsplash.com/photo-1469041797191-50ace28483c3?w=900&q=80&auto=format&fit=crop", accent:"sand" },
  { n:"12", kicker:"Conversation", title:"On AI and the soft edges of a journey — a note from Selin", excerpt:"We use AI for the smart logistics. Never for the calls that matter. Why the soul of the trip has to stay human, and what that actually looks like on day three.", read:"6 min", author:"Selin Tapıcı", date:"Sep · 2025", img:"https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=900&q=80&auto=format&fit=crop", accent:"red" },
];

export const JOURNAL_FILTERS = ["Latest", "Guides", "Field notes", "Versus", "Safety", "Conversation"];
export const EXPERIENCE_FILTERS = ["All", "Wild", "Coast", "Wellness", "Romance", "With Kids", "Long-stay", "Bucket List"];
export const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
