export type ArticleBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "pull"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "table"; head: string[]; rows: string[][] }
  | { type: "divider" };

export type JournalArticle = {
  slug: string;
  body: ArticleBlock[];
};

export const ARTICLES: Record<string, JournalArticle> = {

  "three-quiet-cafes-nairobi": {
    slug: "three-quiet-cafes-nairobi",
    body: [
      { type: "p", text: "Nairobi has a coffee problem — or rather, it has a coffee abundance problem. There are too many places claiming to be specialty, too many playlists turned up too loud, too many exposed-brick rooms full of people on calls. This is a list of the ones that got it right." },
      { type: "p", text: "All three are in the western suburbs — Karen, Lavington, Kilimani — the corridor most of our clients stay in and the part of the city that rewards slow exploration. None of them have a loyalty card." },
      { type: "h2", text: "1. The roastery in Lavington that isn't on the map" },
      { type: "p", text: "A founder we know bought a house in Lavington, realized the garden was larger than the mortgage required, and decided to put a roaster in it. That's the entire origin story. The coffee is Kenyan — AA grade, washed, processed in Kiambu County — and it's exceptional in the way that things grown at altitude and roasted by someone who cares always are." },
      { type: "p", text: "You find it by following your nose, or by knowing someone who knows. There are four tables. The owner usually comes out to talk about the crop. There is no wi-fi password because there is no wi-fi. This is, obviously, the point." },
      { type: "p", text: "Go between 8 and 10am. Take a book. Order the filter. Don't ask for oat milk — they don't have it and they're not sorry." },
      { type: "pull", text: "The coffee is Kenyan AA, washed, grown in Kiambu. It's exceptional in the way things grown at altitude and roasted by someone who cares always are." },
      { type: "h2", text: "2. The courtyard in Karen" },
      { type: "p", text: "Karen was Nairobi before Nairobi was Nairobi. The suburb named after Karen Blixen still has the wide roads, the old jacaranda trees, and the sense that everything is slightly further apart than it needs to be. The café we're pointing you to is inside a compound that used to be a residence, and it still feels like one." },
      { type: "p", text: "The courtyard is the thing. It's shaded by a fig tree that was clearly here before the café, before the house, probably before Karen herself. There are birds — Fischer's lovebirds mostly, occasionally a hadada ibis that arrives without warning and leaves very loudly." },
      { type: "p", text: "The eggs are the best in Nairobi. We have tested this claim empirically over six years. Scrambled, with sourdough from their own bakery, and a side of something green from the garden. Order a long black alongside and consider cancelling your afternoon." },
      { type: "h2", text: "3. The corner in Kilimani" },
      { type: "p", text: "Kilimani is denser, faster, more urban than Karen or Lavington — the part of Nairobi that feels most like a proper city neighbourhood. The bakery-café on the corner of Argwings Kodhek has been there for eleven years, which in Nairobi café terms means it has been through three full cycles of the scene." },
      { type: "p", text: "It's where everyone ends up. The architects from the office upstairs at 10am. The journalist from the NGO next door at 1pm. The two women who have been meeting on Thursdays since 2019 at 3pm. You'll know you're in the right place because the pastries in the window look slightly imperfect in a way that means they were made this morning." },
      { type: "p", text: "The mandazi are the thing to order — not the European pastries, not the 'artisan' anything. The mandazi with black tea, Kenyan style, two teaspoons of sugar, no argument." },
      { type: "h2", text: "A note on Nairobi café culture" },
      { type: "p", text: "Kenya is one of the world's great coffee-growing nations and has, until very recently, exported almost everything it grew. What's happening now — the slow return of good Kenyan coffee to Nairobi — is worth paying attention to. The beans you'll drink at these three places are the same beans that win international auctions. They just never used to stay." },
      { type: "p", text: "We'll update this list as we find places that deserve to be on it. We remove places without ceremony when they stop being worth your time." },
    ],
  },

  "boutique-stays-closest-friends": {
    slug: "boutique-stays-closest-friends",
    body: [
      { type: "p", text: "When a close friend asks where to stay in Kenya, the answer changes. The brochure disappears. The 'well-reviewed' property we'd never choose ourselves disappears. What's left is a short list of places we'd genuinely go back to — or that we wish we'd found sooner." },
      { type: "p", text: "These are twelve of them. Some are bookable directly. Some require a call. Some are not publicly listed at all, which is why they appear in this guide and not in a search engine." },
      { type: "h2", text: "In the Masai Mara" },
      { type: "p", text: "Sala's Camp sits on the Sand River in the private conservancy below the Mara. Six tents. No children under twelve. The guide-to-guest ratio is one-to-one, which is what makes the difference between a game drive and a genuine wildlife education. The crossing position during migration is the best we've found — the guides have been watching this specific curve of the river for years." },
      { type: "p", text: "Angama Mara is the other one. It's more visible — Condé Nast, Instagram, the Out of Africa ridge — but it earned that visibility. The two suites at the far end of the deck have views that don't exist in any other camp. The photography guides are the best in Kenya, full stop." },
      { type: "pull", text: "These aren't properties we've reviewed. They're properties we've slept in, eaten in, driven out of at 5:30am. The list is short because the standards are high." },
      { type: "h2", text: "On the coast" },
      { type: "p", text: "Peponi Hotel in Lamu has been run by the Korschen family since 1967. Carol and Jan are still there. The channel terrace at breakfast is the reason people keep coming back — the dhow traffic in the morning, the light, the calamari at lunch. Ask for a room that faces the water. The ones that don't are also fine, but the ones that do are the reason you came." },
      { type: "p", text: "Kinondo Kwetu on Galu Beach is what happens when a Danish couple buys a stretch of coastline and refuses to compromise on anything. Horses on the beach at sunset. An organic kitchen garden that actually supplies the kitchen. A reef. The kind of property that sounds like it was invented by a marketing team but wasn't." },
      { type: "h2", text: "In Nairobi" },
      { type: "p", text: "Hemingways Nairobi in Karen is the only hotel in Nairobi we recommend unreservedly for first-time visitors. Forty-five suites, a rooftop bar that works, a location that puts you fifteen minutes from the Giraffe Centre and twenty from JKIA. The breakfast is the best hotel breakfast in the city. We've checked." },
      { type: "h2", text: "The ones we don't publish" },
      { type: "p", text: "There are three properties on our internal list that we don't name publicly — one in the Laikipia plateau, one in Lamu, one near Nanyuki. They have five to eight rooms between them. They fill entirely on word of mouth. We send clients to them when the fit is right and when we know the clients well enough to know it's right." },
      { type: "p", text: "If you want to know which ones they are, start the planner and we'll have that conversation." },
    ],
  },

  "women-travelers-kenya": {
    slug: "women-travelers-kenya",
    body: [
      { type: "p", text: "This piece was written by Wanjiku Mwangi, who was born in Nairobi, has guided women travelers across East Africa for eleven years, and has no patience for the kind of travel writing that makes Kenya sound like a survivable expedition rather than a destination." },
      { type: "p", text: "Kenya is safe. The version of safety that matters — the day-to-day, practical, what-do-I-do-now version — is what this piece is about." },
      { type: "h2", text: "Nairobi: the honest version" },
      { type: "p", text: "The western suburbs — Karen, Lavington, Westlands, Kilimani — are the areas most visitors stay in, and they're genuinely fine to navigate. Restaurants, cafés, supermarkets, all within walking distance or a short Bolt (the local Uber equivalent). Walking alone in daylight is normal. Walking at night in these areas is fine if you're on a lit street with other people around; less fine down unlit residential roads where there aren't." },
      { type: "p", text: "We recommend Bolt over taxis for all in-city travel. The app tracks your journey, the driver is rated, and prices are fixed before you get in. Share your trip with someone for anything after 9pm." },
      { type: "p", text: "The CBD (Central Business District) is a different environment — busy, crowded, and fine in daylight, but not where you want to be with a visible camera or an open handbag at rush hour. If you're going to the CBD, go with purpose and go like a local: phone in pocket, bag closed." },
      { type: "pull", text: "Kenya is safe. The practical, day-to-day version of safety is what matters — and it's different from the version travel warnings describe." },
      { type: "h2", text: "On the coast" },
      { type: "p", text: "Diani Beach is one of the easiest destinations in East Africa for solo women. The beach is public, the resort hotels have security, and the Diani beach strip has enough restaurants and bars that you're never walking somewhere isolated. The beach vendors are persistent but not threatening — a firm 'Hapana asante' (no thank you) is understood and respected." },
      { type: "p", text: "Lamu requires one adjustment: dress modestly in the old town. Not at the beach, not at your hotel — but in Lamu Old Town proper, shoulders and knees covered. This is a Muslim community with a 700-year continuous culture; the small courtesy costs nothing and opens every door. Women who make this adjustment report that Lamu is one of the warmest, most welcoming places they've ever been." },
      { type: "h2", text: "In the bush" },
      { type: "p", text: "Camps and lodges are the safest environments in Kenya. Your guide is with you. The camp is fenced or has security. You are the guest and you are looked after. Solo women at small bush camps are extremely well cared for — the culture of hospitality in well-run Kenyan camps is real." },
      { type: "p", text: "Do not walk outside a camp at night without a guide escort. This is not about people — it's about animals. The escort isn't courtesy, it's protocol, and every camp takes it seriously." },
      { type: "h2", text: "Numbers to have" },
      { type: "ul", items: [
        "Emergency: 999 (Kenya Police) or 112 (general emergency)",
        "Tourist Police Helpline: +254 20 604 767",
        "Your hotel or camp's front desk — always",
        "Selin's WhatsApp — we stay available throughout your trip",
      ]},
      { type: "h2", text: "What we tell every woman we send to Kenya" },
      { type: "p", text: "Trust your instincts. If a driver feels wrong, don't get in. If a stretch of beach feels empty in a way that makes you uneasy, walk back. Your read of a situation is usually correct. The incidents that happen to travelers in Kenya are almost always the ones where someone ignored a feeling." },
      { type: "p", text: "And then: go. Kenya is one of the best destinations in the world for women traveling solo, in pairs, or with children. The fear around African travel is largely inherited from people who haven't been. The women who come back are almost always the ones who want to come back soonest." },
    ],
  },

  "diani-or-watamu": {
    slug: "diani-or-watamu",
    body: [
      { type: "p", text: "We get asked this question roughly three times a week. It's the right question — the two stretches of coast are genuinely different, and the wrong choice for your group is a real thing." },
      { type: "p", text: "This is the comparison we actually make internally when we're routing a trip. Not a marketing comparison. Not 'both are lovely in their own way.' The real one." },
      { type: "h2", text: "The basic geography" },
      { type: "p", text: "Diani is on the south coast — 30km south of Mombasa, accessible via the Likoni ferry or a short flight to Ukunda airstrip. It's a 17km beach strip with a reef running parallel about 500 metres offshore. The town of Diani is behind the beach: restaurants, supermarkets, pharmacies, nightlife." },
      { type: "p", text: "Watamu is on the north coast — 120km north of Mombasa, accessible via Malindi airstrip. It's smaller, quieter, and sits inside a UNESCO Biosphere Reserve. The marine park starts at the beach steps. There is no strip. There are a few restaurants and that's about it." },
      { type: "table",
        head: ["", "Diani", "Watamu"],
        rows: [
          ["Vibe", "Lively beach resort", "Quiet eco village"],
          ["Beach", "17km white sand", "3km, more secluded"],
          ["Reef", "500m offshore", "Directly at beach"],
          ["Restaurants", "20+ options", "4–5 reliable spots"],
          ["Walking to dinner", "Yes, easily", "Limited, better with car"],
          ["Nightlife", "Bars, beach clubs", "Almost none"],
          ["Kite-surfing", "World-class conditions", "Not ideal"],
          ["Marine life", "Good", "Exceptional (turtles, whale sharks)"],
          ["Families", "Great (larger resorts, pools)", "Great (calm water, turtle walks)"],
          ["Honeymooners", "If you want some life around you", "If you want total quiet"],
          ["Solo travelers", "Easy, social", "Peaceful, slower"],
          ["Internet/connectivity", "Reliable", "Patchy in places"],
        ]
      },
      { type: "h2", text: "Who we send to Diani" },
      { type: "p", text: "Diani is for people who want a proper beach holiday with options. You can kitesurf in the morning, eat at a different restaurant every night, hire a motorbike and explore south towards Funzi Island, and have a drink somewhere with other people around. It's social and it works." },
      { type: "p", text: "Families with teenagers do well in Diani — there's enough to do that nobody is bored. Couples who want the beach but not isolation. Anyone for whom 'quiet' translates to 'nothing to do' rather than 'peaceful.'" },
      { type: "pull", text: "Watamu is for the people who arrive wanting less and leave realising they wanted exactly this. Diani is for the people who want to be on the Kenyan coast with some life around them." },
      { type: "h2", text: "Who we send to Watamu" },
      { type: "p", text: "Watamu is for people who will be genuinely happy with a reef, a book, and the knowledge that the chef at their lodge is good. The marine park is world-class — turtles nesting from October to March, whale sharks at the same time, coral gardens that haven't been touched by mass tourism. If snorkeling or diving is the point, there's no contest." },
      { type: "p", text: "Couples who want to completely disconnect. Families with younger children who will be thrilled by turtle nesting walks and don't need a kids club. Writers and photographers. People who've done beach resorts and want something quieter and more real." },
      { type: "h2", text: "The one we usually do" },
      { type: "p", text: "For a 10-night trip ending on the coast, we often do five nights in Watamu followed by five nights in Diani — or the reverse. You get both. The contrast is part of the experience. The bush flight between them is 45 minutes if you come via Mombasa." },
      { type: "p", text: "If you only have five nights on the coast, Watamu for content, Diani for ease. That's the honest answer." },
    ],
  },

  "weekend-in-iten": {
    slug: "weekend-in-iten",
    body: [
      { type: "p", text: "Iten sits at 2,400 metres in the Elgeyo Escarpment, in the Rift Valley highlands of western Kenya. From the town's edge you can see down into the valley floor, a 2,000-metre drop over a few kilometres of escarpment. The view is the first thing people come for. The running is why they stay." },
      { type: "p", text: "This is where the world's fastest distance runners train. Not in a facility — on the roads, the tracks, the red dirt paths that connect Iten to the surrounding villages. At 6am on a Saturday, you'll share the road with 200 athletes. Most of them are unknown outside Kenya. Some will win major city marathons before the year is out." },
      { type: "h2", text: "Getting there" },
      { type: "p", text: "Iten is a four-and-a-half-hour drive from Nairobi, or a short flight to Eldoret followed by a 40-minute drive. The road from Eldoret is good. The escarpment descent into the Kerio Valley, if you continue past Iten, is one of the most dramatic drives in East Africa and worth doing once." },
      { type: "p", text: "We recommend driving from Nairobi on the Friday evening and staying two nights. One full day is not enough." },
      { type: "h2", text: "What a day in Iten looks like" },
      { type: "p", text: "Wake up early — 5:30am if you want to be out before the training groups. The temperature at altitude is cool enough for a jacket at that hour. Walk or run the red dirt tracks north of town: you'll pass schoolchildren, women carrying water, and athletes running in clusters of five or ten, talking quietly in Kalenjin." },
      { type: "p", text: "The High Altitude Training Centre on the edge of town has a track that's open most mornings. The centre's resident coach, if he's around and you ask politely, will sometimes talk through training methodology with visitors. This is a rare thing. Don't waste it by asking for selfies." },
      { type: "pull", text: "At 6am on a Saturday, you share the road with 200 athletes. Most are unknown outside Kenya. Some will win major city marathons before the year is out." },
      { type: "h2", text: "The food" },
      { type: "p", text: "Ugali with sukuma wiki. Mandazi with Kenyan tea. This is what the athletes eat and it's what you'll find at the local canteens. There are two or three restaurants in Iten proper; none are remarkable but all are honest. Bring some snacks from Nairobi if you're particular about variety." },
      { type: "h2", text: "What this trip is and isn't" },
      { type: "p", text: "It's not a tourist experience in the conventional sense — there's no visitor centre, no organised tours, no infrastructure built around seeing the runners. That's the point. You're going to a working training community and watching something real happen at altitude. The access is complete because there are no barriers, no stages, no performance. The athletes are training. You're just there." },
      { type: "p", text: "We include Iten as an extension on some of our longer itineraries — particularly for clients who run, who follow athletics, or who want to see a part of Kenya that no tour brochure has reached. It pairs well with the Kerio Valley and an overnight at one of the camps on the valley floor before continuing west or returning to Nairobi." },
    ],
  },

  "single-mother-safari": {
    slug: "single-mother-safari",
    body: [
      { type: "p", text: "The question isn't whether Kenya works for a mother traveling alone with children. It does, extraordinarily well, when it's planned correctly. The question is: what does 'planned correctly' mean when you're the only adult in the group?" },
      { type: "p", text: "We've run this plan more than two dozen times. Here's the framework." },
      { type: "h2", text: "The hidden tax" },
      { type: "p", text: "Solo travel with children isn't expensive in the way people expect. The hotel room is more expensive, yes — you need a family suite rather than a double. But the real cost is invisible: it's the cognitive load of being the only adult. Every decision, every transfer, every medication schedule, every meltdown at the airstrip is yours alone." },
      { type: "p", text: "The way we reduce that tax isn't by making you pay more — it's by removing the decisions. When everything is pre-arranged, briefed, and confirmed, you're not traveling as a logistics coordinator who happens to have children. You're traveling as a parent on holiday." },
      { type: "pull", text: "The real cost of solo parent travel isn't money — it's cognitive load. We remove the decisions so you can be a parent on holiday, not a project manager with children." },
      { type: "h2", text: "The framework" },
      { type: "ul", items: [
        "Single entry point: one WhatsApp thread with Selin for the entire trip. Not a call centre, not a ticketing system — one person who knows your children's names and your pediatrician's number.",
        "Pre-arrival briefing call: 30 minutes before departure, we walk through every transfer, every check-in procedure, every driver's name. Nothing is a surprise.",
        "Family-specialist guides: not every Mara guide is good with children. We book the ones who are. The guides who know how to talk about dung beetles to a six-year-old are not the same as the guides who know how to talk about migration patterns to an adult.",
        "Pediatrician on call: we provide the number of a Nairobi-based pediatrician who does phone and WhatsApp consultations. This is not a medical referral service — it's a doctor who knows Kenya, knows the altitude effects, knows the malaria risk windows.",
        "Gated accommodation: all our family properties have either fenced perimeters, locked pool areas, or both. We check this before we book.",
        "No shared transfers: solo parents with children don't go in shared vehicles. Private car, private driver, driver's name and photo sent the night before.",
      ]},
      { type: "h2", text: "The camps that work" },
      { type: "p", text: "Not all Mara camps take children. Of those that do, not all have thought about what that actually means. The camps we use for solo parent trips have connecting tents or family suites (so children and parent are in the same space or directly adjacent), a pool with supervision, and a guide team that's been through child-appropriate wildlife interpretation." },
      { type: "p", text: "Governors' Camp is our first choice for solo parent families in the Mara. The structure of the camp, the family suite availability, and the guide team make it the most reliable option. Hemingways Watamu on the coast has been the most consistent family beach property we've used." },
      { type: "h2", text: "The ages" },
      { type: "p", text: "Under 5: the Mara drives are long and the animals are not on a schedule. We recommend Nairobi + coast for very young children, with the Giraffe Centre and DSWT as the wildlife element. These are curated, short, and reliably excellent for small children." },
      { type: "p", text: "5–10: the full arc works. A good guide makes game drives work for this age group. Snorkeling at Watamu is possible from age 7 with a guide. The Maasai village visit is consistently the highlight for this age." },
      { type: "p", text: "10+: Kenya is theirs. This is the age group that leaves wanting to come back and often does, years later, independently." },
    ],
  },

  "letter-maasai-guide": {
    slug: "letter-maasai-guide",
    body: [
      { type: "p", text: "James ole Kimani has been guiding in the Masai Mara for twenty-two years. He grew up in a manyatta near the Sand River, tracked his first lion on foot at fourteen, and passed his Kenya Wildlife Service certification at nineteen. We sat with him under a fig tree on the edge of the Mara North conservancy for an afternoon in December and asked him to talk. This is an edited version of what he said." },
      { type: "pull", text: "\"The bush doesn't lie to you. The guests often do — they tell you they want to see everything. What they actually want is to feel something. My job is to give them the feeling, not the checklist.\"" },
      { type: "h2", text: "On what's changed" },
      { type: "p", text: "\"When I started, the guests had film cameras. They had maybe thirty-six shots. They were very careful. Now everyone has a phone that can take ten thousand pictures, and sometimes I think they see less because of it. They're looking at the screen, not at the animal. I've started telling people: put the phone down for the first five minutes after we stop. Just look. The animal isn't going anywhere.\"" },
      { type: "p", text: "\"The vehicles have changed more than the animals. When I started, we had old Land Rovers with manual everything. Now some camps have electric vehicles, very quiet, which is actually better — the lions don't notice us as much. But the new vehicles are too comfortable. People fall asleep on the afternoon drive. I understand this — they woke up at 5am — but the elephant is right there.\"" },
      { type: "h2", text: "On the migration" },
      { type: "p", text: "\"The migration is not a show. It doesn't happen because tourists are watching. The wildebeest cross the river because the grass is better on the other side, and they die in the river because there are crocodiles, and they cross anyway because hunger is stronger than fear. This is the whole story of the Mara, if you understand it. Everything else follows from this.\"" },
      { type: "p", text: "\"The best crossing I ever saw was in September 2019. I had a family — two parents, three children. We waited at the crossing for four hours. The children played cards in the vehicle. Then 40,000 wildebeest crossed in forty minutes. The children threw away the cards. The father cried. I cried a little. I'm not ashamed of this.\"" },
      { type: "h2", text: "On what the bush teaches" },
      { type: "p", text: "\"I have seen more death in this bush than most people see in a lifetime. Lions, leopards, crocodiles, hyenas — they all kill, and they kill in front of you. The guests sometimes find this difficult. I tell them: this is not violence. This is the system. The wildebeest feeds the lion, the lion feeds the vulture, the vulture feeds the ground, the ground feeds the grass, the grass feeds the wildebeest. If you can see the whole circle, you can stop being frightened of any one part of it.\"" },
      { type: "p", text: "\"What the bush teaches me, every year, is patience. The animal is on its schedule, not mine. The guest wants to see the leopard at 7am. The leopard will show itself when it decides to show itself. My job is to put us in the right place and then wait. The waiting is the skill. The seeing is the reward.\"" },
      { type: "h2", text: "On the future" },
      { type: "p", text: "\"My son is eight. He wants to be a guide. I'm training him already — not formally, just walking. I show him how to read the grass when an elephant has passed, how to tell the difference between a lion print from this morning and one from yesterday. He learns fast. This knowledge — it has to pass. If my son doesn't carry it, it goes somewhere else.\"" },
      { type: "p", text: "\"The Mara will be here after all of us. It was here before the camps, before the tourists, before Kenya was a country. What I hope is that it stays wild enough that my son's children can do what I do. That's all.\"" },
    ],
  },

  "mara-conservancies-ranked": {
    slug: "mara-conservancies-ranked",
    body: [
      { type: "p", text: "The Masai Mara ecosystem covers roughly 1,500 square kilometres of the national reserve, plus another 1,600+ kilometres of private conservancies bordering it. The conservancies are where we spend most of our time — lower vehicle density, off-road driving allowed, walking safaris possible, night drives permitted. The reserve proper has none of these." },
      { type: "p", text: "Here's how we actually compare the main conservancies when we're building an itinerary." },
      { type: "h2", text: "Olare Motorogi Conservancy" },
      { type: "p", text: "4,500 acres on the northern border of the reserve. One of the oldest and most established private conservancies. Low vehicle quota — around 9 camps total, each with strict limits. The big cats in Olare Motorogi are among the most habituated in the ecosystem, which means vehicles can get closer without disturbing behaviour. Off-road driving, night drives, walking safaris all available." },
      { type: "p", text: "Who it's for: photographers, returning visitors, anyone who's already done the main reserve and wants the real private experience. Camp quality is consistently high — Mahali Mzuri, Mara Plains Camp, Cottar's 1920s." },
      { type: "h2", text: "Naboisho Conservancy" },
      { type: "p", text: "50,000 acres — by far the largest of the main conservancies. This means fewer vehicles per acre than anywhere else in the ecosystem. On a quiet day in Naboisho you can drive for three hours without seeing another vehicle. The downside: the cats are less habituated than in Olare Motorogi, so sightings require more patience." },
      { type: "p", text: "Who it's for: clients who prioritise solitude over cat density. The landscape is the story here — rolling savannah, minimal infrastructure, the feeling of being genuinely alone in the wild." },
      { type: "pull", text: "The conservancy you choose changes the trip more than the camp you choose. We've seen clients have a mediocre week in a great camp because the conservancy was wrong for them." },
      { type: "h2", text: "Mara North Conservancy" },
      { type: "p", text: "75,000 acres north of the reserve. The most diverse habitat in the ecosystem — riverine forest, open plains, rocky outcrops. This means the widest range of species, including leopard in the forest areas and cheetah on the open plains. The conservancy borders Laikipia to the north, and the landscape transitions visibly." },
      { type: "p", text: "Who it's for: first-time visitors who want to see the breadth of the Mara ecosystem, and anyone particularly interested in leopard or cheetah." },
      { type: "h2", text: "Mara Triangle (the reserve's western sector)" },
      { type: "p", text: "Technically part of the reserve, managed by the Mara Conservancy (a nonprofit). The triangle sits between the Mara River and the Tanzania border — the classic migration crossing territory. Angama Mara sits above it on the Oloololo Escarpment; the camp's famous ridge view looks down over this entire section." },
      { type: "p", text: "Who it's for: the migration. If river crossings are the reason you're coming, the Triangle is where you're going. Outside migration season (July–October), the vehicle density is manageable. Inside it, the Triangle can be busy — but what you're there to see is happening, so it's worth it." },
      { type: "h2", text: "The honest summary" },
      { type: "table",
        head: ["Conservancy", "Size", "Vehicle density", "Best for"],
        rows: [
          ["Olare Motorogi", "4,500 acres", "Very low", "Photography, cat sightings"],
          ["Naboisho", "50,000 acres", "Lowest", "Solitude, landscape"],
          ["Mara North", "75,000 acres", "Low", "First timers, diversity"],
          ["Mara Triangle", "Reserve sector", "Moderate–high (peak)", "Migration crossings"],
        ]
      },
      { type: "p", text: "We mix conservancies on longer itineraries — two nights in Mara North, two in Olare Motorogi, for example. The contrast is interesting and the two ecosystems feel genuinely different." },
    ],
  },

  "dhow-boys-lamu": {
    slug: "dhow-boys-lamu",
    body: [
      { type: "p", text: "The dhow is the oldest technology still operating daily on the Kenyan coast. The design hasn't changed meaningfully in 1,200 years — a lateen sail, a carved wooden hull, a shallow draft that can navigate the mangrove channels and the open ocean with equal ease. The men who crew them learned from their fathers, who learned from theirs. This is not a metaphor. It is literally true." },
      { type: "p", text: "In Lamu, the dhow is still how cargo moves, how fish arrives, how the outer islands communicate. The tourist dhow — the sunset cruise, the snorkel trip to Manda Tidal Flat — exists alongside all of this and doesn't displace it. This is unusual. Most coastal destinations kill the authentic version when the tourist version arrives. Lamu hasn't, mostly because the island has no roads and therefore can't scale up fast enough to destroy itself." },
      { type: "h2", text: "How the boats work" },
      { type: "p", text: "A typical Lamu dhow carries a crew of two — a captain and a mate. The captain steers and reads the wind; the mate adjusts the sail and handles the anchor. On a tourist boat for a half-day trip, the captain usually speaks enough English to explain what he's doing. On a working boat, he won't and doesn't need to." },
      { type: "p", text: "The lateen sail catches wind from the side, which is why dhows can tack into the wind more efficiently than a square-rigged vessel. The captains know the channels of the Lamu archipelago in a way that doesn't reduce to GPS — they read the water colour, the wave pattern, the behaviour of birds. Captain Ali, who we book for most of our clients, has been on this water since he was eleven years old. He's now thirty-seven." },
      { type: "pull", text: "The dhow captains read the water colour, the wave pattern, the behaviour of birds. GPS is for the day-trippers from Malindi. The Lamu captains navigate by knowledge." },
      { type: "h2", text: "Sunset is at 6pm" },
      { type: "p", text: "The title of this piece comes from something Captain Ali told us three years ago. We'd asked about timing the sunset cruise. He said: 'Sunset is at six. Every day, six o'clock. You don't need to check the internet.' He wasn't being dismissive — he was making the point that the equatorial light is predictable in a way that northern latitudes aren't. Six o'clock, give or take six minutes, every evening, all year." },
      { type: "p", text: "The best sunset cruise in Lamu leaves at 5pm, goes north through the mangrove channel, and anchors at a point where the sun drops behind the Shela dunes. If you time it correctly, the light on the water lasts for twenty minutes after the sun disappears. These are the twenty minutes that people describe when they try to explain Lamu to people who haven't been." },
      { type: "h2", text: "What to pay" },
      { type: "p", text: "The going rate for a half-day dhow hire (4 hours, 2–4 people) is between $60 and $100 depending on the season and the captain. Full-day rates are $150–$200. These are honest rates — don't negotiate below them. The captains have families and fuel costs. The margin on a sunset cruise is thin." },
      { type: "p", text: "Tip separately at the end. A good tip is $15–$25 on a half-day. If the captain found you a good sandbank and the light was right, be generous. These things aren't guaranteed and he did the work." },
      { type: "h2", text: "The captain we always call first" },
      { type: "p", text: "Captain Ali Aboud. He's been on the water since he was eleven. He knows the sandbanks that are only exposed at low tide, the channels that most captains avoid because the coral is close, the exact spot on the Shela shoreline where the colour of the water changes from green to deep blue. We've put over a hundred of our clients on his boat. Not one has been disappointed." },
      { type: "p", text: "We'll pass his number along when you book with us. The best captains in Lamu now book up four days in advance in high season (December–March, July–August). We block the dates early." },
    ],
  },

  "what-it-costs-kenya": {
    slug: "what-it-costs-kenya",
    body: [
      { type: "p", text: "We're going to tear apart three real itineraries — the $9,000 trip, the $18,000 trip, and the $42,000 trip — and show you exactly where the money went. The numbers are per-couple, excluding international flights, unless noted. These are from 2025–2026 bookings." },
      { type: "p", text: "The point isn't to shock you with the high number or reassure you with the low one. The point is to show you that the difference between them is real — and that you can make intelligent choices about where it matters to you." },
      { type: "h2", text: "The $9,000 trip — 8 nights, couple" },
      { type: "p", text: "Nairobi (2 nights) → Masai Mara (3 nights, mid-range camp) → Diani (3 nights)." },
      { type: "table",
        head: ["Item", "Cost"],
        rows: [
          ["Nairobi hotel × 2 nights (Karen, B&B)", "$480"],
          ["Bush flight NBI → Mara → Diani", "$820"],
          ["Mara camp × 3 nights (full board, shared vehicle)", "$3,600"],
          ["Diani hotel × 3 nights (half board)", "$1,200"],
          ["Giraffe Centre + DSWT entrance", "$80"],
          ["Transfers (all)", "$320"],
          ["Guide tips + camp tips", "$300"],
          ["Miscellaneous (drinks, market, SIM)", "$200"],
          ["MyKenya concierge fee", "$600"],
          ["Total", "$7,600"],
        ]
      },
      { type: "p", text: "The shared vehicle in the Mara is the main cost lever here — on a shared game drive you're with up to 6 guests, which limits how long you can wait at a sighting and where you can go. It's still excellent. It's just not private." },
      { type: "h2", text: "The $18,000 trip — 10 nights, couple" },
      { type: "p", text: "Nairobi (1 night) → Mara private conservancy (4 nights, private vehicle) → Lamu (5 nights)." },
      { type: "table",
        head: ["Item", "Cost"],
        rows: [
          ["Nairobi hotel × 1 night (Hemingways)", "$320"],
          ["Bush flights (Wilson → Mara → Lamu → NBI)", "$1,400"],
          ["Mara camp × 4 nights (full board, private vehicle + guide)", "$8,800"],
          ["Lamu stone house × 5 nights (half board)", "$3,200"],
          ["Sunset dhow + snorkel trip", "$240"],
          ["Couples massage in-tent", "$180"],
          ["All transfers", "$480"],
          ["Tips (guide, camp, boat captain)", "$600"],
          ["MyKenya concierge fee", "$900"],
          ["Total", "$16,120"],
        ]
      },
      { type: "pull", text: "The private vehicle in the Mara is where you feel the difference. You wait as long as you want. You go off-road when the guide reads a track. You eat breakfast where the animals are, not where the kitchen planned." },
      { type: "h2", text: "The $42,000 trip — 12 nights, couple" },
      { type: "p", text: "Nairobi (2 nights, Hemingways + Giraffe Manor) → Mara (4 nights, top-tier camp, private) → Lamu (4 nights, private house) → Samburu (2 nights)." },
      { type: "table",
        head: ["Item", "Cost"],
        rows: [
          ["Giraffe Manor overnight (2 guests)", "$2,800"],
          ["Hemingways Nairobi extra night", "$380"],
          ["All private charter flights", "$6,200"],
          ["Mara camp (Angama/Sala's, full board, private)", "$14,400"],
          ["Lamu private house (exclusive use, 2 guests)", "$4,800"],
          ["Samburu camp × 2 nights (full board, private)", "$4,200"],
          ["DSWT elephant orphanage exclusive visit", "$600"],
          ["Hot-air balloon Mara", "$800"],
          ["All transfers (private, named drivers)", "$960"],
          ["In-tent spa × 2 sessions", "$360"],
          ["Tips (full arc)", "$1,200"],
          ["MyKenya concierge fee", "$1,800"],
          ["Total", "$38,500"],
        ]
      },
      { type: "h2", text: "What the difference actually buys" },
      { type: "ul", items: [
        "From $9k to $18k: the private vehicle. This is the biggest single quality jump in a Kenya trip.",
        "From $18k to $42k: the tier of camp, the Giraffe Manor overnight, the private charter (no shared planes), the exclusive house in Lamu instead of a hotel room.",
        "The concierge fee covers the briefing call, the on-ground coordination, the 3am call if something goes wrong, and Selin's personal knowledge of every property on the list.",
      ]},
      { type: "p", text: "None of these numbers include international flights, which for London–Nairobi–London run $800–$1,800 per person depending on airline and timing. We can advise on optimal routing but don't book international flights directly." },
    ],
  },

  "driving-in-kenya": {
    slug: "driving-in-kenya",
    body: [
      { type: "p", text: "We are sometimes asked about self-driving in Kenya. Our honest answer: it's possible, it can be great, and there are specific situations where we recommend it. There are also situations where we actively discourage it, and we're going to tell you what those are." },
      { type: "h2", text: "The roads" },
      { type: "p", text: "Kenya has one genuinely excellent road (the Nairobi–Mombasa highway, tarmac, mostly well-maintained). Several good main roads (Nairobi–Nakuru, Nairobi–Thika). And a large number of roads that are 'roads' in the sense that vehicles have driven them before, which is different from the sense in which they are maintained, signposted, or reliable after rain." },
      { type: "p", text: "The bush roads — the ones that connect camps in the Mara, the tracks in Laikipia, the coastal laterite roads north of Malindi — require a 4×4, local knowledge, and ideally someone in the passenger seat who can read the ruts. They're not dangerous if you know them. They're very expensive if you don't (recovery fees, tyre replacement, a day lost waiting for help)." },
      { type: "h2", text: "The driving culture" },
      { type: "p", text: "Kenyan roads are driven assertively. Overtaking on blind corners is normal. Trucks travel slowly in the left lane and move right without much warning. Matatus (minibuses) operate on schedules known only to themselves. At night, vehicles often drive without working headlights." },
      { type: "p", text: "None of this is particularly dangerous if you understand it and drive defensively. It's stressful if you don't, and it will use cognitive bandwidth you'd rather spend on the landscape." },
      { type: "pull", text: "The question isn't whether you can drive in Kenya. It's whether the driving is the best use of your time, your energy, and your attention on the days you'd be doing it." },
      { type: "h2", text: "When we recommend self-driving" },
      { type: "ul", items: [
        "Extended stays in a single location (a villa in Diani for two weeks, where you're making short, familiar trips to the supermarket and restaurants)",
        "Nairobi urban navigation, for clients who are comfortable with city driving and want the flexibility",
        "The Nairobi–Nakuru–Naivasha loop, which is on good tarmac and very manageable for confident drivers",
        "Returning visitors who know the roads and find driving independently part of the pleasure",
      ]},
      { type: "h2", text: "When we don't" },
      { type: "ul", items: [
        "Long transfers (Nairobi to the coast by road is 8+ hours; a bush flight is 55 minutes — the road is not the point)",
        "Bush camp access roads, especially after rain",
        "Any trip where the client is jet-lagged on arrival and needs to drive immediately",
        "Night driving outside urban areas — the risk of livestock on the road is real and the consequences are serious",
        "Multi-destination itineraries where the driving is the majority of the experience and the destinations are the minority",
      ]},
      { type: "h2", text: "Our default" },
      { type: "p", text: "Our default is a named private driver for all ground transfers and a trusted guide vehicle for all bush driving. The drivers we use are KWS-certified for bush environments, know the camps and their access roads, and are reachable by us at all times. The cost difference between a private driver and a rental car is smaller than most people expect — and the value difference is significant." },
      { type: "p", text: "The one stretch of road we still drive ourselves, when we're travelling: the descent from Iten into the Kerio Valley. It's one of the most dramatic drives in East Africa and it's best appreciated slowly, with stops, at your own pace. Everything else, we'd rather have someone else do." },
    ],
  },

  "ai-soft-edges-journey": {
    slug: "ai-soft-edges-journey",
    body: [
      { type: "p", text: "This is a note I've been meaning to write since we added the AI planner to MyKenya. Not to defend it — it doesn't need defending, it's useful — but to be clear about what it does and doesn't do, and why I think the distinction matters." },
      { type: "h2", text: "What AI is good at" },
      { type: "p", text: "AI is good at structure. Given your dates, your group size, your budget range, your stated preferences, and a database of properties we've vetted, it can generate a competent initial route in seconds. It knows that a 7-night trip with three regions is too rushed. It knows that the Mara in April is rained on. It knows that a bush flight from Wilson to Lamu takes under an hour and that a road transfer takes a day." },
      { type: "p", text: "This is genuinely useful. The planning work that used to take an experienced consultant two hours takes the planner two minutes — which means I can spend those two hours on something the planner can't do." },
      { type: "pull", text: "AI handles the structure. I handle the call on day three when the guide says the crossing might happen tomorrow and you need to decide whether to extend by a day. That call is mine." },
      { type: "h2", text: "What it's not good at" },
      { type: "p", text: "It doesn't know that you cried at a migration crossing video I sent you last year. It doesn't know that your husband gets altitude sickness above 2,500 metres, something you mentioned in passing during our first call. It doesn't know that your daughter is terrified of loud birds (important in a camp where hadada ibises land at 5am). It doesn't know that you'd been planning this trip for seven years and that the reason you're going now is something you'd rather not put in a form." },
      { type: "p", text: "The AI handles the data. I handle the context. These are not the same thing, and conflating them is where AI-assisted travel planning goes wrong." },
      { type: "h2", text: "Day three" },
      { type: "p", text: "Day three of a Kenya trip is usually when something needs adjusting. Not going wrong — adjusting. The guide thinks the migration might shift east. The rains came early and the road to the next camp is muddy. The children are more tired than expected and need a slow morning. Your partner wants to stay one more night in the Mara and skip the coast." },
      { type: "p", text: "The AI can't make that call. I can, because I've made it before, because I know the camps and their flexibility, because I know what can be moved and what can't, and because I've been on the phone with the camp manager at that moment and know how it goes." },
      { type: "h2", text: "Why I'm not worried about it" },
      { type: "p", text: "Some travel businesses are replacing their human judgment with AI and hoping the difference doesn't show. It does. A Kenya trip is not a hotel booking. It's a live environment where animals move, weather changes, camps open and close, guides have varying expertise, and the difference between a good experience and a great one is often a single call made at the right moment by someone with the right information." },
      { type: "p", text: "AI makes me faster. It doesn't make me unnecessary. I'm comfortable with that distinction. I've been living with it for two years and I think it's the right model." },
      { type: "p", text: "The planner is the beginning of the conversation. The conversation is the point." },
      { type: "p", text: "— Selin" },
    ],
  },

};
