export type Stay = {
  id: string;
  slug: string;
  featured?: boolean;
  cat: string;
  catKey: string;
  nights: string;
  title: string;
  sub: string;
  region: string;
  from: number;
  orig?: number;
  currency: string;
  rating: number;
  reviews: number;
  includes: string[];
  host: string;
  badges: string[];
  imgSrc: string;
};

export const CATEGORIES = [
  { key: "all",     label: "All stays",        count: 18 },
  { key: "camp",    label: "Tented Camps",      count: 6  },
  { key: "coast",   label: "Coast & Beach",     count: 5  },
  { key: "lodge",   label: "Bush Lodges",       count: 4  },
  { key: "town",    label: "Town Houses",        count: 2  },
  { key: "villa",   label: "Private Villas",    count: 1  },
];

export const STAYS: Stay[] = [
  {
    id: "camp-01",
    slug: "sand-river-masai-mara",
    featured: true,
    cat: "TENTED CAMP",
    catKey: "camp",
    nights: "3–5 NIGHTS",
    title: "Sand River Masai Mara",
    sub: "Eight tents on the Mara River — private conservancy, migration front-row, no fences.",
    region: "Masai Mara",
    from: 1200,
    currency: "USD",
    rating: 4.97,
    reviews: 214,
    includes: [
      "All meals & sundowner drinks",
      "Twice-daily private game drives (4×4)",
      "Maasai guide — KWS certified",
      "Bush breakfast & sundowner setup",
      "Airstrip transfers included",
      "Migration river crossing positioning",
    ],
    host: "Camp Manager: John Ole Tipis · 12 yrs Mara",
    badges: ["Eco Certified", "Relais & Châteaux", "Private Conservancy"],
    imgSrc: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&q=80&auto=format&fit=crop",
  },
  {
    id: "coast-01",
    slug: "the-sands-at-nomad-diani",
    featured: true,
    cat: "BEACH RESORT",
    catKey: "coast",
    nights: "5–10 NIGHTS",
    title: "The Sands at Nomad · Diani",
    sub: "Adults-only on Diani's best stretch — barefoot luxury, reef snorkeling, dhow dinners.",
    region: "Diani Beach",
    from: 480,
    currency: "USD",
    rating: 4.93,
    reviews: 178,
    includes: [
      "Beachfront cottage or villa",
      "Full breakfast daily",
      "Snorkeling & water sports",
      "Reef dhow excursion (1×)",
      "Kitesurf lesson (1×)",
      "Airport transfers (MBA ↔ property)",
    ],
    host: "General Manager: Aisha Mwangi · 9 yrs hospitality",
    badges: ["Eco Certified", "Travel + Leisure"],
    imgSrc: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop",
  },
  {
    id: "lodge-01",
    slug: "ol-pejeta-wilderness",
    cat: "BUSH LODGE",
    catKey: "lodge",
    nights: "3–5 NIGHTS",
    title: "Ol Pejeta Wilderness · Nanyuki",
    sub: "Rhino conservancy, equator crossing, chimpanzee sanctuary — all in one private concession.",
    region: "Nanyuki / Laikipia",
    from: 860,
    currency: "USD",
    rating: 4.91,
    reviews: 142,
    includes: [
      "All meals & local drinks",
      "Game drives in private conservancy",
      "Chimpanzee sanctuary walk",
      "Sweetwaters sundowner (rhino in view)",
      "Night game drive with spotlight",
      "Transfers from Nanyuki airstrip",
    ],
    host: "Head Guide: Samuel Kariuki · Laikipia specialist",
    badges: ["Big Five", "Rhino Conservancy", "LEWA Neighbour"],
    imgSrc: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop",
  },
  {
    id: "town-01",
    slug: "peponi-hotel-lamu",
    cat: "BOUTIQUE HOTEL",
    catKey: "town",
    nights: "4–7 NIGHTS",
    title: "Peponi Hotel · Lamu",
    sub: "Iconic Swahili stone house on the channel — dhow racing views, mangrove creeks, slow Lamu pace.",
    region: "Lamu Island",
    from: 290,
    currency: "USD",
    rating: 4.95,
    reviews: 312,
    includes: [
      "Room in restored Swahili stone house",
      "Full breakfast on the terrace",
      "Sunset dhow cruise (1×)",
      "Creek kayaking with guide",
      "Donkey-and-walk old town tour",
      "Ferry from Lamu airstrip",
    ],
    host: "Owner: Carol & Jan Korschen · Lamu since 1967",
    badges: ["Condé Nast Traveller", "UNESCO Neighbour"],
    imgSrc: "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900&q=80&auto=format&fit=crop",
  },
  {
    id: "camp-02",
    slug: "cottar-1920s-camp",
    cat: "TENTED CAMP",
    catKey: "camp",
    nights: "3–5 NIGHTS",
    title: "Cottar's 1920s Camp · South Mara",
    sub: "The oldest family-run camp in Africa — private conservancy, zero carbon, Edwardian canvas.",
    region: "Masai Mara South",
    from: 1540,
    orig: 1800,
    currency: "USD",
    rating: 4.98,
    reviews: 97,
    includes: [
      "All meals, wines & spirits",
      "Private vehicle & guide for all drives",
      "Bush walks with armed Maasai escort",
      "Picnic breakfasts in the bush",
      "Community visit & bead workshop",
      "Wi-Fi free — full disconnect",
    ],
    host: "Host: Calvin Cottar · 4th generation · Africa expert",
    badges: ["Condé Nast Traveller", "Eco Gold", "Travelife"],
    imgSrc: "https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&q=80&auto=format&fit=crop",
  },
  {
    id: "coast-02",
    slug: "turtle-bay-watamu",
    cat: "ECO LODGE",
    catKey: "coast",
    nights: "4–7 NIGHTS",
    title: "Turtle Bay · Watamu",
    sub: "Marine park at the door — turtle nesting beach, coral snorkeling, creek boat trips, real slow.",
    region: "Watamu",
    from: 210,
    currency: "USD",
    rating: 4.88,
    reviews: 203,
    includes: [
      "Half board (breakfast & dinner)",
      "Marine park snorkeling × 2",
      "Creek boat trip with birdguide",
      "Turtle nest night walk (seasonal)",
      "Bodaboda village cycling",
      "Transfer from MYD airstrip",
    ],
    host: "Eco Manager: Dr. Shau Wa Mwamba · marine biologist",
    badges: ["Eco Certified", "Marine Park Partner"],
    imgSrc: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80&auto=format&fit=crop",
  },
  {
    id: "camp-03",
    slug: "amboseli-porini",
    cat: "TENTED CAMP",
    catKey: "camp",
    nights: "3–4 NIGHTS",
    title: "Amboseli Porini Camp",
    sub: "Elephant herds and Kilimanjaro silhouettes — Maasai-owned, community funded, zero-fence.",
    region: "Amboseli",
    from: 720,
    currency: "USD",
    rating: 4.90,
    reviews: 156,
    includes: [
      "All meals & local drinks",
      "Game drives (AM & PM) in private conservancy",
      "Maasai village cultural walk",
      "Kilimanjaro sunrise breakfast setup",
      "Sundowner with Kili view",
      "Amboseli airstrip transfers",
    ],
    host: "Camp Conservancy: OlKiombo Maasai Group Ranch",
    badges: ["Community Owned", "Big Five", "Porini Collection"],
    imgSrc: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=80&auto=format&fit=crop",
  },
  {
    id: "lodge-02",
    slug: "naivasha-loldia-house",
    cat: "BUSH LODGE",
    catKey: "lodge",
    nights: "2–3 NIGHTS",
    title: "Loldia House · Naivasha",
    sub: "Edwardian farmhouse on Lake Naivasha — hippos at dawn, flamingo boat, Hell's Gate cycling.",
    region: "Naivasha",
    from: 340,
    currency: "USD",
    rating: 4.89,
    reviews: 88,
    includes: [
      "All meals & house wines",
      "Boat trip on Naivasha (2× daily)",
      "Hell's Gate cycling with guide",
      "Crescent Island game walk",
      "Night game drive on farm",
      "Nairobi airport transfers (2.5 hrs)",
    ],
    host: "House Manager: Lucy Wanjiku · 15 yrs Naivasha",
    badges: ["Historic House", "Flamingo Lake", "Basecamp partner"],
    imgSrc: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=900&q=80&auto=format&fit=crop",
  },
  {
    id: "villa-01",
    slug: "the-house-diani",
    featured: true,
    cat: "PRIVATE VILLA",
    catKey: "villa",
    nights: "5–14 NIGHTS",
    title: "The House · Diani",
    sub: "Six-bedroom private villa on Diani — full staff, pool on the beach, your schedule entirely.",
    region: "Diani Beach",
    from: 3200,
    currency: "USD",
    rating: 5.00,
    reviews: 24,
    includes: [
      "Exclusive-use villa (up to 12 guests)",
      "Full chef, housekeeping & butler",
      "Unlimited soft drinks, wine cellar",
      "Dhow & fishing boat on request",
      "Safari day trips arranged",
      "Mombasa airport transfers (all guests)",
    ],
    host: "Villa Manager: Fatuma Said · 11 yrs private estates",
    badges: ["Exclusive Use", "Private Chef", "Adults or Families"],
    imgSrc: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop",
  },
  {
    id: "coast-03",
    slug: "majlis-resort-lamu",
    cat: "BEACH RESORT",
    catKey: "coast",
    nights: "4–7 NIGHTS",
    title: "Majlis Resort · Manda Island",
    sub: "Manda Island — Lamu's quieter neighbour. Swahili architecture, coral pool, dhow at the jetty.",
    region: "Lamu Archipelago",
    from: 380,
    currency: "USD",
    rating: 4.92,
    reviews: 134,
    includes: [
      "Half board (breakfast & dinner)",
      "Dhow trip to Lamu old town",
      "Snorkeling on Manda tidal flats",
      "Mangrove creek walk",
      "Cooking class with chef Amina",
      "Lamu airstrip boat transfer",
    ],
    host: "General Manager: Ahmed Al-Majlis · island host",
    badges: ["Condé Nast Listed", "Swahili Architecture"],
    imgSrc: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=900&q=80&auto=format&fit=crop",
  },
];
